package thaumcraft.common.config;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumRarity;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.common.blocks.BlockAiry;
import thaumcraft.common.blocks.BlockAiryItem;
import thaumcraft.common.blocks.BlockAlchemyFurnace;
import thaumcraft.common.blocks.BlockArcaneDoor;
import thaumcraft.common.blocks.BlockArcaneFurnace;
import thaumcraft.common.blocks.BlockCandle;
import thaumcraft.common.blocks.BlockCandleItem;
import thaumcraft.common.blocks.BlockChestHungry;
import thaumcraft.common.blocks.BlockCosmeticOpaque;
import thaumcraft.common.blocks.BlockCosmeticOpaqueItem;
import thaumcraft.common.blocks.BlockCosmeticSolid;
import thaumcraft.common.blocks.BlockCosmeticSolidItem;
import thaumcraft.common.blocks.BlockCosmeticStairs;
import thaumcraft.common.blocks.BlockCosmeticStoneSlab;
import thaumcraft.common.blocks.BlockCosmeticStoneSlabItem;
import thaumcraft.common.blocks.BlockCosmeticWoodSlab;
import thaumcraft.common.blocks.BlockCosmeticWoodSlabItem;
import thaumcraft.common.blocks.BlockCrystal;
import thaumcraft.common.blocks.BlockCrystalItem;
import thaumcraft.common.blocks.BlockCustomOre;
import thaumcraft.common.blocks.BlockCustomOreItem;
import thaumcraft.common.blocks.BlockCustomPlant;
import thaumcraft.common.blocks.BlockCustomPlantItem;
import thaumcraft.common.blocks.BlockEldritch;
import thaumcraft.common.blocks.BlockEldritchItem;
import thaumcraft.common.blocks.BlockEldritchNothing;
import thaumcraft.common.blocks.BlockEldritchPortal;
import thaumcraft.common.blocks.BlockEssentiaReservoir;
import thaumcraft.common.blocks.BlockEssentiaReservoirItem;
import thaumcraft.common.blocks.BlockFluidDeath;
import thaumcraft.common.blocks.BlockFluidPure;
import thaumcraft.common.blocks.BlockFluxGas;
import thaumcraft.common.blocks.BlockFluxGasItem;
import thaumcraft.common.blocks.BlockFluxGoo;
import thaumcraft.common.blocks.BlockFluxGooItem;
import thaumcraft.common.blocks.BlockHole;
import thaumcraft.common.blocks.BlockJar;
import thaumcraft.common.blocks.BlockJarItem;
import thaumcraft.common.blocks.BlockLifter;
import thaumcraft.common.blocks.BlockLoot;
import thaumcraft.common.blocks.BlockLootItem;
import thaumcraft.common.blocks.BlockMagicBox;
import thaumcraft.common.blocks.BlockMagicalLeaves;
import thaumcraft.common.blocks.BlockMagicalLeavesItem;
import thaumcraft.common.blocks.BlockMagicalLog;
import thaumcraft.common.blocks.BlockMagicalLogItem;
import thaumcraft.common.blocks.BlockManaPod;
import thaumcraft.common.blocks.BlockMetalDevice;
import thaumcraft.common.blocks.BlockMetalDeviceItem;
import thaumcraft.common.blocks.BlockMirror;
import thaumcraft.common.blocks.BlockMirrorItem;
import thaumcraft.common.blocks.BlockStoneDevice;
import thaumcraft.common.blocks.BlockStoneDeviceItem;
import thaumcraft.common.blocks.BlockTable;
import thaumcraft.common.blocks.BlockTableItem;
import thaumcraft.common.blocks.BlockTaint;
import thaumcraft.common.blocks.BlockTaintFibres;
import thaumcraft.common.blocks.BlockTaintFibresItem;
import thaumcraft.common.blocks.BlockTaintItem;
import thaumcraft.common.blocks.BlockTube;
import thaumcraft.common.blocks.BlockTubeItem;
import thaumcraft.common.blocks.BlockWarded;
import thaumcraft.common.blocks.BlockWoodenDevice;
import thaumcraft.common.blocks.BlockWoodenDeviceItem;
import thaumcraft.common.blocks.CustomStepSound;
import thaumcraft.common.tiles.TileAlchemyFurnace;
import thaumcraft.common.tiles.TileAlchemyFurnaceAdvanced;
import thaumcraft.common.tiles.TileAlchemyFurnaceAdvancedNozzle;
import thaumcraft.common.tiles.TileAlembic;
import thaumcraft.common.tiles.TileArcaneBore;
import thaumcraft.common.tiles.TileArcaneBoreBase;
import thaumcraft.common.tiles.TileArcaneFurnace;
import thaumcraft.common.tiles.TileArcaneFurnaceNozzle;
import thaumcraft.common.tiles.TileArcaneLamp;
import thaumcraft.common.tiles.TileArcaneLampFertility;
import thaumcraft.common.tiles.TileArcaneLampGrowth;
import thaumcraft.common.tiles.TileArcanePressurePlate;
import thaumcraft.common.tiles.TileArcaneWorkbench;
import thaumcraft.common.tiles.TileBanner;
import thaumcraft.common.tiles.TileBellows;
import thaumcraft.common.tiles.TileBrainbox;
import thaumcraft.common.tiles.TileCentrifuge;
import thaumcraft.common.tiles.TileChestHungry;
import thaumcraft.common.tiles.TileCrucible;
import thaumcraft.common.tiles.TileCrystal;
import thaumcraft.common.tiles.TileDeconstructionTable;
import thaumcraft.common.tiles.TileEldritchAltar;
import thaumcraft.common.tiles.TileEldritchCap;
import thaumcraft.common.tiles.TileEldritchCrabSpawner;
import thaumcraft.common.tiles.TileEldritchCrystal;
import thaumcraft.common.tiles.TileEldritchLock;
import thaumcraft.common.tiles.TileEldritchNothing;
import thaumcraft.common.tiles.TileEldritchObelisk;
import thaumcraft.common.tiles.TileEldritchPortal;
import thaumcraft.common.tiles.TileEldritchTrap;
import thaumcraft.common.tiles.TileEssentiaCrystalizer;
import thaumcraft.common.tiles.TileEssentiaReservoir;
import thaumcraft.common.tiles.TileEtherealBloom;
import thaumcraft.common.tiles.TileFluxScrubber;
import thaumcraft.common.tiles.TileFocalManipulator;
import thaumcraft.common.tiles.TileGrate;
import thaumcraft.common.tiles.TileHole;
import thaumcraft.common.tiles.TileInfusionMatrix;
import thaumcraft.common.tiles.TileInfusionPillar;
import thaumcraft.common.tiles.TileJarBrain;
import thaumcraft.common.tiles.TileJarFillable;
import thaumcraft.common.tiles.TileJarFillableVoid;
import thaumcraft.common.tiles.TileJarNode;
import thaumcraft.common.tiles.TileLifter;
import thaumcraft.common.tiles.TileMagicBox;
import thaumcraft.common.tiles.TileMagicWorkbenchCharger;
import thaumcraft.common.tiles.TileManaPod;
import thaumcraft.common.tiles.TileMirror;
import thaumcraft.common.tiles.TileMirrorEssentia;
import thaumcraft.common.tiles.TileNitor;
import thaumcraft.common.tiles.TileNode;
import thaumcraft.common.tiles.TileNodeConverter;
import thaumcraft.common.tiles.TileNodeEnergized;
import thaumcraft.common.tiles.TileNodeStabilizer;
import thaumcraft.common.tiles.TileOwned;
import thaumcraft.common.tiles.TilePedestal;
import thaumcraft.common.tiles.TileResearchTable;
import thaumcraft.common.tiles.TileSensor;
import thaumcraft.common.tiles.TileSpa;
import thaumcraft.common.tiles.TileTable;
import thaumcraft.common.tiles.TileThaumatorium;
import thaumcraft.common.tiles.TileThaumatoriumTop;
import thaumcraft.common.tiles.TileTube;
import thaumcraft.common.tiles.TileTubeBuffer;
import thaumcraft.common.tiles.TileTubeFilter;
import thaumcraft.common.tiles.TileTubeOneway;
import thaumcraft.common.tiles.TileTubeRestrict;
import thaumcraft.common.tiles.TileTubeValve;
import thaumcraft.common.tiles.TileVisRelay;
import thaumcraft.common.tiles.TileWandPedestal;
import thaumcraft.common.tiles.TileWarded;
import thaumcraft.common.tiles.TileWardingStone;
import thaumcraft.common.tiles.TileWardingStoneFence;

public class ConfigBlocks {
   public static Fluid FLUXGOO = (new Fluid("fluxGoo")).setGaseous(false).setLuminosity(7).setDensity(8).setViscosity(6000);
   public static Fluid FLUXGAS = (new Fluid("fluxGas")).setGaseous(true).setLuminosity(7).setDensity(-4).setViscosity(2500);
   public static Fluid FLUIDPURE;
   public static Fluid FLUIDDEATH;
   public static Block blockFluxGoo;
   public static Block blockFluxGas;
   public static Block blockFluidPure;
   public static Block blockFluidDeath;
   public static Block blockHole;
   public static Block blockArcaneFurnace;
   public static Block blockMetalDevice;
   public static Block blockMagicalLog;
   public static Block blockStoneDevice;
   public static Block blockWoodenDevice;
   public static Block blockMagicalLeaves;
   public static Block blockTable;
   public static Block blockChestHungry;
   public static Block blockCustomOre;
   public static Block blockCustomPlant;
   public static Block blockCandle;
   public static Block blockJar;
   public static Block blockArcaneDoor;
   public static Block blockWarded;
   public static Block blockLifter;
   public static Block blockAiry;
   public static Block blockCrystal;
   public static Block blockCosmeticOpaque;
   public static Block blockCosmeticSolid;
   public static Block blockMirror;
   public static Block blockTaint;
   public static Block blockTaintFibres;
   public static Block blockManaPod;
   public static Block blockTube;
   public static Block blockMagicBox;
   public static Block blockEldritch;
   public static Block blockEldritchPortal;
   public static Block blockEssentiaReservoir;
   public static Block blockStairsArcaneStone;
   public static Block blockStairsSilverwood;
   public static Block blockStairsGreatwood;
   public static Block blockStairsEldritch;
   public static Block blockSlabWood;
   public static Block blockSlabStone;
   public static Block blockDoubleSlabWood;
   public static Block blockDoubleSlabStone;
   public static Block blockEldritchNothing;
   public static Block blockAlchemyFurnace;
   public static Block blockLootUrn;
   public static Block blockLootCrate;
   public static int blockCosmeticOpaqueRI;
   public static int blockWoodenDeviceRI;
   public static int blockLifterRI;
   public static int blockCrystalRI;
   public static int blockFluxGasRI;
   public static int blockCustomOreRI;
   public static int blockTaintRI;
   public static int blockTaintFibreRI;
   public static int blockMirrorRI;
   public static int blockCandleRI;
   public static int blockWardedRI;
   public static int blockArcaneFurnaceRI;
   public static int blockMetalDeviceRI;
   public static int blockStoneDeviceRI;
   public static int blockChestHungryRI;
   public static int blockTableRI;
   public static int blockJarRI;
   public static int blockLootUrnRI;
   public static int blockLootCrateRI;
   public static int blockTubeRI;
   public static int blockEssentiaReservoirRI;
   public static int blockEldritchRI;

   public static void init() {
      initializeBlocks();
      registerBlocks();
      registerTileEntities();
      blockCustomOre.setHarvestLevel("pickaxe", 2, 0);
      blockCustomOre.setHarvestLevel("pickaxe", 2, 7);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.bed);
      ThaumcraftApi.portableHoleBlackList.add(blockEldritch);
      ThaumcraftApi.portableHoleBlackList.add(blockEldritchPortal);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.piston);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.piston_head);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.sticky_piston);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.piston_extension);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.wooden_door);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.iron_door);
      ThaumcraftApi.portableHoleBlackList.add(blockFluxGoo);
      ThaumcraftApi.portableHoleBlackList.add(blockFluxGas);
      ThaumcraftApi.portableHoleBlackList.add(blockArcaneFurnace);
   }

   private static void initializeBlocks() {
      FluidRegistry.registerFluid(FLUXGOO);
      FluidRegistry.registerFluid(FLUIDPURE);
      FluidRegistry.registerFluid(FLUIDDEATH);
      blockFluxGoo = (new BlockFluxGoo()).setBlockName("blockFluxGoo");
      blockFluxGas = (new BlockFluxGas()).setBlockName("blockFluxGas");
      blockHole = (new BlockHole()).setBlockName("blockHole");
      blockCustomOre = (new BlockCustomOre()).setBlockName("blockCustomOre");
      blockCustomPlant = (new BlockCustomPlant()).setBlockName("blockCustomPlant");
      blockMagicalLog = (new BlockMagicalLog()).setBlockName("blockMagicalLog");
      blockMagicalLeaves = (new BlockMagicalLeaves()).setBlockName("blockMagicalLeaves");
      blockArcaneFurnace = (new BlockArcaneFurnace()).setBlockName("blockArcaneFurnace");
      blockMetalDevice = (new BlockMetalDevice()).setBlockName("blockMetalDevice");
      blockAlchemyFurnace = (new BlockAlchemyFurnace()).setBlockName("blockAlchemyFurnace");
      blockTable = (new BlockTable()).setBlockName("blockTable");
      blockChestHungry = (new BlockChestHungry()).setBlockName("blockChestHungry");
      blockCandle = (new BlockCandle()).setBlockName("blockCandle");
      blockJar = (new BlockJar()).setBlockName("blockJar");
      blockArcaneDoor = (new BlockArcaneDoor()).setBlockName("blockArcaneDoor");
      blockWoodenDevice = (new BlockWoodenDevice()).setBlockName("blockWoodenDevice");
      blockLifter = (new BlockLifter()).setBlockName("blockLifter");
      blockAiry = (new BlockAiry()).setBlockName("blockAiry");
      blockCrystal = (new BlockCrystal()).setBlockName("blockCrystal");
      blockCosmeticOpaque = (new BlockCosmeticOpaque()).setBlockName("blockCosmeticOpaque");
      blockCosmeticSolid = (new BlockCosmeticSolid()).setBlockName("blockCosmeticSolid");
      blockMirror = (new BlockMirror()).setBlockName("blockMirror");
      blockTaint = (new BlockTaint()).setBlockName("blockTaint");
      blockTaintFibres = (new BlockTaintFibres()).setBlockName("blockTaintFibres");
      blockStoneDevice = (new BlockStoneDevice()).setBlockName("blockStoneDevice");
      blockManaPod = (new BlockManaPod()).setBlockName("blockManaPod");
      blockTube = (new BlockTube()).setBlockName("blockTube");
      blockWarded = (new BlockWarded()).setBlockName("blockWarded");
      blockMagicBox = (new BlockMagicBox()).setBlockName("blockMagicBox");
      blockFluidPure = (new BlockFluidPure()).setBlockName("blockFluidPure");
      blockFluidDeath = (new BlockFluidDeath()).setBlockName("blockFluidDeath");
      blockEldritch = (new BlockEldritch()).setBlockName("blockEldritch");
      blockEldritchPortal = (new BlockEldritchPortal()).setBlockName("blockPortalEldritch");
      blockEssentiaReservoir = (new BlockEssentiaReservoir()).setBlockName("blockEssentiaReservoir");
      blockEldritchNothing = (new BlockEldritchNothing()).setBlockName("blockPortalNothing");
      blockStairsArcaneStone = (new BlockCosmeticStairs(blockCosmeticSolid, 7)).setBlockName("blockStairsArcaneStone");
      blockStairsGreatwood = (new BlockCosmeticStairs(blockWoodenDevice, 6)).setBlockName("blockStairsGreatwood");
      blockStairsSilverwood = (new BlockCosmeticStairs(blockWoodenDevice, 7)).setBlockName("blockStairsSilverwood");
      blockStairsEldritch = (new BlockCosmeticStairs(blockCosmeticSolid, 11)).setBlockName("blockStairsEldritch");
      blockSlabWood = (new BlockCosmeticWoodSlab(false)).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setBlockName("blockCosmeticSlabWood");
      blockSlabStone = (new BlockCosmeticStoneSlab(false)).setHardness(2.0F).setResistance(10.0F).setStepSound(Block.soundTypePiston).setBlockName("blockCosmeticSlabStone");
      blockDoubleSlabWood = (new BlockCosmeticWoodSlab(true)).setHardness(2.0F).setResistance(5.0F).setStepSound(Block.soundTypeWood).setBlockName("blockCosmeticDoubleSlabWood");
      blockDoubleSlabStone = (new BlockCosmeticStoneSlab(true)).setHardness(2.0F).setResistance(10.0F).setStepSound(Block.soundTypePiston).setBlockName("blockCosmeticDoubleSlabStone");
      blockLootUrn = (new BlockLoot(Material.clay, "urn", 1)).setStepSound(new CustomStepSound("urnbreak", 1.0F, 0.7F)).setBlockName("blockLootUrn");
      blockLootCrate = (new BlockLoot(Material.wood, "crate", 2)).setStepSound(Block.soundTypeWood).setBlockName("blockLootCrate");
   }

   private static void registerBlocks() {
      GameRegistry.registerBlock(blockFluxGoo, BlockFluxGooItem.class, "blockFluxGoo");
      GameRegistry.registerBlock(blockFluxGas, BlockFluxGasItem.class, "blockFluxGas");
      GameRegistry.registerBlock(blockFluidPure, "blockFluidPure");
      GameRegistry.registerBlock(blockFluidDeath, "blockFluidDeath");
      GameRegistry.registerBlock(blockCustomOre, BlockCustomOreItem.class, "blockCustomOre");
      GameRegistry.registerBlock(blockMagicalLog, BlockMagicalLogItem.class, "blockMagicalLog");
      GameRegistry.registerBlock(blockMagicalLeaves, BlockMagicalLeavesItem.class, "blockMagicalLeaves");
      GameRegistry.registerBlock(blockCustomPlant, BlockCustomPlantItem.class, "blockCustomPlant");
      GameRegistry.registerBlock(blockTaint, BlockTaintItem.class, "blockTaint");
      GameRegistry.registerBlock(blockTaintFibres, BlockTaintFibresItem.class, "blockTaintFibres");
      GameRegistry.registerBlock(blockCosmeticOpaque, BlockCosmeticOpaqueItem.class, "blockCosmeticOpaque");
      GameRegistry.registerBlock(blockCosmeticSolid, BlockCosmeticSolidItem.class, "blockCosmeticSolid");
      GameRegistry.registerBlock(blockCrystal, BlockCrystalItem.class, "blockCrystal");
      GameRegistry.registerBlock(blockTube, BlockTubeItem.class, "blockTube");
      GameRegistry.registerBlock(blockMetalDevice, BlockMetalDeviceItem.class, "blockMetalDevice");
      GameRegistry.registerBlock(blockWoodenDevice, BlockWoodenDeviceItem.class, "blockWoodenDevice");
      GameRegistry.registerBlock(blockStoneDevice, BlockStoneDeviceItem.class, "blockStoneDevice");
      GameRegistry.registerBlock(blockMirror, BlockMirrorItem.class, "blockMirror");
      GameRegistry.registerBlock(blockTable, BlockTableItem.class, "blockTable");
      GameRegistry.registerBlock(blockChestHungry, "blockChestHungry");
      GameRegistry.registerBlock(blockArcaneDoor, "blockArcaneDoor");
      GameRegistry.registerBlock(blockLifter, "blockLifter");
      GameRegistry.registerBlock(blockMagicBox, "blockMagicBox");
      GameRegistry.registerBlock(blockAlchemyFurnace, "blockAlchemyFurnace");
      GameRegistry.registerBlock(blockJar, BlockJarItem.class, "blockJar");
      GameRegistry.registerBlock(blockCandle, BlockCandleItem.class, "blockCandle");
      GameRegistry.registerBlock(blockEldritch, BlockEldritchItem.class, "blockEldritch");
      GameRegistry.registerBlock(blockAiry, BlockAiryItem.class, "blockAiry");
      GameRegistry.registerBlock(blockManaPod, "blockManaPod");
      GameRegistry.registerBlock(blockArcaneFurnace, "blockArcaneFurnace");
      GameRegistry.registerBlock(blockWarded, "blockWarded");
      GameRegistry.registerBlock(blockHole, "blockHole");
      GameRegistry.registerBlock(blockEldritchPortal, "blockPortalEldritch");
      GameRegistry.registerBlock(blockEssentiaReservoir, BlockEssentiaReservoirItem.class, "blockEssentiaReservoir");
      GameRegistry.registerBlock(blockEldritchNothing, "blockEldritchNothing");
      GameRegistry.registerBlock(blockStairsArcaneStone, "blockStairsArcaneStone");
      GameRegistry.registerBlock(blockStairsGreatwood, "blockStairsGreatwood");
      GameRegistry.registerBlock(blockStairsSilverwood, "blockStairsSilverwood");
      GameRegistry.registerBlock(blockStairsEldritch, "blockStairsEldritch");
      GameRegistry.registerBlock(blockSlabWood, BlockCosmeticWoodSlabItem.class, "blockCosmeticSlabWood");
      GameRegistry.registerBlock(blockSlabStone, BlockCosmeticStoneSlabItem.class, "blockCosmeticSlabStone");
      GameRegistry.registerBlock(blockDoubleSlabWood, "blockCosmeticDoubleSlabWood");
      GameRegistry.registerBlock(blockDoubleSlabStone, "blockCosmeticDoubleSlabStone");
      GameRegistry.registerBlock(blockLootUrn, BlockLootItem.class, "blockLootUrn");
      GameRegistry.registerBlock(blockLootCrate, BlockLootItem.class, "blockLootCrate");
   }

   private static void registerTileEntities() {
      GameRegistry.registerTileEntity(TileHole.class, "TileHole");
      GameRegistry.registerTileEntity(TileArcaneFurnace.class, "TileArcaneFurnace");
      GameRegistry.registerTileEntity(TileArcaneFurnaceNozzle.class, "TileArcaneFurnaceNozzle");
      GameRegistry.registerTileEntity(TileCrucible.class, "TileCrucible");
      GameRegistry.registerTileEntity(TileAlembic.class, "TileSiphon");
      GameRegistry.registerTileEntity(TileJarFillable.class, "TileJar");
      GameRegistry.registerTileEntity(TileJarFillableVoid.class, "TileJarVoid");
      GameRegistry.registerTileEntity(TileJarNode.class, "TileJarNode");
      GameRegistry.registerTileEntity(TileJarBrain.class, "TileJarBrain");
      GameRegistry.registerTileEntity(TileResearchTable.class, "TileResearchTable");
      GameRegistry.registerTileEntity(TileTable.class, "TileTable");
      GameRegistry.registerTileEntity(TileArcaneWorkbench.class, "TileArcaneWorkbench");
      GameRegistry.registerTileEntity(TileChestHungry.class, "TileChestHungry");
      GameRegistry.registerTileEntity(TileBellows.class, "TileBellows");
      GameRegistry.registerTileEntity(TileSensor.class, "TileSensor");
      GameRegistry.registerTileEntity(TileArcanePressurePlate.class, "TileArcanePressurePlate");
      GameRegistry.registerTileEntity(TileArcaneBore.class, "TileArcaneBore");
      GameRegistry.registerTileEntity(TileArcaneBoreBase.class, "TileArcaneBoreBase");
      GameRegistry.registerTileEntity(TileArcaneLamp.class, "TileArcaneLamp");
      GameRegistry.registerTileEntity(TileArcaneLampGrowth.class, "TileArcaneLampGrowth");
      GameRegistry.registerTileEntity(TileArcaneLampFertility.class, "TileArcaneLampFertility");
      GameRegistry.registerTileEntity(TileOwned.class, "TileOwned");
      GameRegistry.registerTileEntity(TileLifter.class, "TileLifter");
      GameRegistry.registerTileEntity(TileNitor.class, "TileNitor");
      GameRegistry.registerTileEntity(TileNode.class, "TileNode");
      GameRegistry.registerTileEntity(TileCrystal.class, "TileCrystal");
      GameRegistry.registerTileEntity(TileEldritchCrystal.class, "TileEldritchCrystal");
      GameRegistry.registerTileEntity(TileMirror.class, "TileMirror");
      GameRegistry.registerTileEntity(TileMirrorEssentia.class, "TileMirrorEssentia");
      GameRegistry.registerTileEntity(TilePedestal.class, "TilePedestal");
      GameRegistry.registerTileEntity(TileWandPedestal.class, "TileWandPedestal");
      GameRegistry.registerTileEntity(TileInfusionMatrix.class, "TileInfusionStone");
      GameRegistry.registerTileEntity(TileInfusionPillar.class, "TileInfusionPillar");
      GameRegistry.registerTileEntity(TileAlchemyFurnace.class, "TileAlchemyFurnace");
      GameRegistry.registerTileEntity(TileAlchemyFurnaceAdvanced.class, "TileAlchemyFurnaceAdvanced");
      GameRegistry.registerTileEntity(TileAlchemyFurnaceAdvancedNozzle.class, "TileAlchemyFurnaceAdvancedNozzle");
      GameRegistry.registerTileEntity(TileDeconstructionTable.class, "TileDeconstructionTable");
      GameRegistry.registerTileEntity(TileEtherealBloom.class, "TilePurifyTotem");
      GameRegistry.registerTileEntity(TileTube.class, "TileTube");
      GameRegistry.registerTileEntity(TileTubeValve.class, "TileTubeValve");
      GameRegistry.registerTileEntity(TileCentrifuge.class, "TileCentrifuge");
      GameRegistry.registerTileEntity(TileTubeFilter.class, "TileTubeFilter");
      GameRegistry.registerTileEntity(TileTubeBuffer.class, "TileTubeBuffer");
      GameRegistry.registerTileEntity(TileTubeRestrict.class, "TileTubeRestrict");
      GameRegistry.registerTileEntity(TileTubeOneway.class, "TileTubeOneway");
      GameRegistry.registerTileEntity(TileThaumatorium.class, "TileThaumatorium");
      GameRegistry.registerTileEntity(TileThaumatoriumTop.class, "TileThaumatoriumTop");
      GameRegistry.registerTileEntity(TileBrainbox.class, "TileBrainbox");
      GameRegistry.registerTileEntity(TileWarded.class, "TileWarded");
      GameRegistry.registerTileEntity(TileGrate.class, "TileGrate");
      GameRegistry.registerTileEntity(TileWardingStone.class, "TileWardingStone");
      GameRegistry.registerTileEntity(TileWardingStoneFence.class, "TileWardingStoneFence");
      GameRegistry.registerTileEntity(TileMagicBox.class, "TileMagicBox");
      GameRegistry.registerTileEntity(TileNodeStabilizer.class, "TileNodeStabilizer");
      GameRegistry.registerTileEntity(TileVisRelay.class, "TileVisRelay");
      GameRegistry.registerTileEntity(TileNodeEnergized.class, "TileNodeEnergized");
      GameRegistry.registerTileEntity(TileNodeConverter.class, "TileNodeConverter");
      GameRegistry.registerTileEntity(TileMagicWorkbenchCharger.class, "TileMagicWorkbenchCharger");
      GameRegistry.registerTileEntity(TileManaPod.class, "TileManaPod");
      GameRegistry.registerTileEntity(TileSpa.class, "TileSpa");
      GameRegistry.registerTileEntity(TileEldritchAltar.class, "TileEldritchAltar");
      GameRegistry.registerTileEntity(TileEldritchObelisk.class, "TileEldritchObelisk");
      GameRegistry.registerTileEntity(TileEldritchCap.class, "TileEldritchCap");
      GameRegistry.registerTileEntity(TileBanner.class, "TileBanner");
      GameRegistry.registerTileEntity(TileEldritchPortal.class, "TileEldritchPortal");
      GameRegistry.registerTileEntity(TileEssentiaReservoir.class, "TileEssentiaReservoir");
      GameRegistry.registerTileEntity(TileEssentiaCrystalizer.class, "TileEssentiaCrystalizer");
      GameRegistry.registerTileEntity(TileEldritchNothing.class, "TileEldritchNothing");
      GameRegistry.registerTileEntity(TileEldritchLock.class, "TileEldritchLock");
      GameRegistry.registerTileEntity(TileEldritchCrabSpawner.class, "TileEldritchCrabSpawner");
      GameRegistry.registerTileEntity(TileFocalManipulator.class, "TileFocalManipulator");
      GameRegistry.registerTileEntity(TileFluxScrubber.class, "TileFluxScrubber");
      GameRegistry.registerTileEntity(TileEldritchTrap.class, "TileEldritchTrap");
   }

   static {
      FLUIDPURE = (new Fluid("fluidPure")).setGaseous(false).setLuminosity(10).setViscosity(1000).setRarity(EnumRarity.rare);
      FLUIDDEATH = (new Fluid("fluidDeath")).setGaseous(false).setLuminosity(8).setViscosity(1500).setRarity(EnumRarity.rare);
      blockCosmeticOpaqueRI = -1;
      blockWoodenDeviceRI = -1;
      blockLifterRI = -1;
      blockCrystalRI = -1;
      blockFluxGasRI = -1;
      blockCustomOreRI = -1;
      blockTaintRI = -1;
      blockTaintFibreRI = -1;
      blockMirrorRI = -1;
      blockCandleRI = -1;
      blockWardedRI = -1;
      blockArcaneFurnaceRI = -1;
      blockMetalDeviceRI = -1;
      blockStoneDeviceRI = -1;
      blockChestHungryRI = -1;
      blockTableRI = -1;
      blockJarRI = -1;
      blockLootUrnRI = -1;
      blockLootCrateRI = -1;
      blockTubeRI = -1;
      blockEssentiaReservoirRI = -1;
      blockEldritchRI = -1;
   }
}
