package thaumcraft.common.config;

import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import java.util.Arrays;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemArmor.ArmorMaterial;
// import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.oredict.OreDictionary;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.wands.StaffRod;
import thaumcraft.api.wands.WandCap;
import thaumcraft.api.wands.WandRod;
import thaumcraft.common.blocks.ItemArcaneDoor;
import thaumcraft.common.blocks.ItemJarFilled;
import thaumcraft.common.blocks.ItemJarNode;
import thaumcraft.common.entities.ItemSpawnerEgg;
import thaumcraft.common.entities.golems.ItemGolemBell;
import thaumcraft.common.entities.golems.ItemGolemCore;
import thaumcraft.common.entities.golems.ItemGolemDecoration;
import thaumcraft.common.entities.golems.ItemGolemPlacer;
import thaumcraft.common.entities.golems.ItemGolemUpgrade;
import thaumcraft.common.entities.golems.ItemTrunkSpawner;
import thaumcraft.common.items.ItemBathSalts;
import thaumcraft.common.items.ItemBottleTaint;
import thaumcraft.common.items.ItemBucketDeath;
import thaumcraft.common.items.ItemBucketPure;
import thaumcraft.common.items.ItemCompassStone;
import thaumcraft.common.items.ItemCrystalEssence;
import thaumcraft.common.items.ItemEldritchObject;
import thaumcraft.common.items.ItemEssence;
import thaumcraft.common.items.ItemInkwell;
import thaumcraft.common.items.ItemKey;
import thaumcraft.common.items.ItemLootBag;
import thaumcraft.common.items.ItemManaBean;
import thaumcraft.common.items.ItemNugget;
import thaumcraft.common.items.ItemNuggetEdible;
import thaumcraft.common.items.ItemResearchNotes;
import thaumcraft.common.items.ItemResource;
import thaumcraft.common.items.ItemSanitySoap;
import thaumcraft.common.items.ItemShard;
import thaumcraft.common.items.ItemTripleMeatTreat;
import thaumcraft.common.items.ItemWispEssence;
import thaumcraft.common.items.ItemZombieBrain;
import thaumcraft.common.items.armor.ItemBootsTraveller;
import thaumcraft.common.items.armor.ItemCultistBoots;
import thaumcraft.common.items.armor.ItemCultistLeaderArmor;
import thaumcraft.common.items.armor.ItemCultistPlateArmor;
import thaumcraft.common.items.armor.ItemCultistRobeArmor;
import thaumcraft.common.items.armor.ItemFortressArmor;
import thaumcraft.common.items.armor.ItemGoggles;
import thaumcraft.common.items.armor.ItemHoverHarness;
import thaumcraft.common.items.armor.ItemRobeArmor;
import thaumcraft.common.items.armor.ItemThaumiumArmor;
import thaumcraft.common.items.armor.ItemVoidArmor;
import thaumcraft.common.items.armor.ItemVoidRobeArmor;
import thaumcraft.common.items.baubles.ItemAmuletRunic;
import thaumcraft.common.items.baubles.ItemAmuletVis;
import thaumcraft.common.items.baubles.ItemBaubleBlanks;
import thaumcraft.common.items.baubles.ItemGirdleHover;
import thaumcraft.common.items.baubles.ItemGirdleRunic;
import thaumcraft.common.items.baubles.ItemRingRunic;
import thaumcraft.common.items.equipment.ItemBowBone;
import thaumcraft.common.items.equipment.ItemCrimsonSword;
import thaumcraft.common.items.equipment.ItemElementalAxe;
import thaumcraft.common.items.equipment.ItemElementalHoe;
import thaumcraft.common.items.equipment.ItemElementalPickaxe;
import thaumcraft.common.items.equipment.ItemElementalShovel;
import thaumcraft.common.items.equipment.ItemElementalSword;
import thaumcraft.common.items.equipment.ItemPrimalArrow;
import thaumcraft.common.items.equipment.ItemPrimalCrusher;
import thaumcraft.common.items.equipment.ItemThaumiumAxe;
import thaumcraft.common.items.equipment.ItemThaumiumHoe;
import thaumcraft.common.items.equipment.ItemThaumiumPickaxe;
import thaumcraft.common.items.equipment.ItemThaumiumShovel;
import thaumcraft.common.items.equipment.ItemThaumiumSword;
import thaumcraft.common.items.equipment.ItemVoidAxe;
import thaumcraft.common.items.equipment.ItemVoidHoe;
import thaumcraft.common.items.equipment.ItemVoidPickaxe;
import thaumcraft.common.items.equipment.ItemVoidShovel;
import thaumcraft.common.items.equipment.ItemVoidSword;
import thaumcraft.common.items.relics.ItemHandMirror;
import thaumcraft.common.items.relics.ItemResonator;
import thaumcraft.common.items.relics.ItemSanityChecker;
import thaumcraft.common.items.relics.ItemThaumometer;
import thaumcraft.common.items.relics.ItemThaumonomicon;
import thaumcraft.common.items.wands.ItemFocusPouchBauble;
import thaumcraft.common.items.wands.ItemWandCap;
import thaumcraft.common.items.wands.ItemWandCasting;
import thaumcraft.common.items.wands.ItemWandRod;
import thaumcraft.common.items.wands.WandRodPrimalOnUpdate;
import thaumcraft.common.items.wands.foci.ItemFocusExcavation;
import thaumcraft.common.items.wands.foci.ItemFocusFire;
import thaumcraft.common.items.wands.foci.ItemFocusFrost;
import thaumcraft.common.items.wands.foci.ItemFocusHellbat;
import thaumcraft.common.items.wands.foci.ItemFocusPech;
import thaumcraft.common.items.wands.foci.ItemFocusPortableHole;
import thaumcraft.common.items.wands.foci.ItemFocusPrimal;
import thaumcraft.common.items.wands.foci.ItemFocusShock;
import thaumcraft.common.items.wands.foci.ItemFocusTrade;
import thaumcraft.common.items.wands.foci.ItemFocusWarding;

public class ConfigItems {
   public static WandCap WAND_CAP_IRON;
   public static WandCap WAND_CAP_COPPER;
   public static WandCap WAND_CAP_GOLD;
   public static WandCap WAND_CAP_SILVER;
   public static WandCap WAND_CAP_THAUMIUM;
   public static WandCap WAND_CAP_VOID;
   public static WandRod WAND_ROD_WOOD;
   public static WandRod WAND_ROD_GREATWOOD;
   public static WandRod WAND_ROD_OBSIDIAN;
   public static WandRod WAND_ROD_BLAZE;
   public static WandRod WAND_ROD_ICE;
   public static WandRod WAND_ROD_QUARTZ;
   public static WandRod WAND_ROD_BONE;
   public static WandRod WAND_ROD_REED;
   public static WandRod WAND_ROD_SILVERWOOD;
   public static StaffRod STAFF_ROD_GREATWOOD;
   public static StaffRod STAFF_ROD_OBSIDIAN;
   public static StaffRod STAFF_ROD_BLAZE;
   public static StaffRod STAFF_ROD_ICE;
   public static StaffRod STAFF_ROD_QUARTZ;
   public static StaffRod STAFF_ROD_BONE;
   public static StaffRod STAFF_ROD_REED;
   public static StaffRod STAFF_ROD_SILVERWOOD;
   public static StaffRod STAFF_ROD_PRIMAL;
   public static Item itemWandCasting;
   public static Item itemWandCap;
   public static Item itemWandRod;
   public static Item itemFocusPouch;
   public static Item itemFocusFire;
   public static Item itemFocusFrost;
   public static Item itemFocusShock;
   public static Item itemFocusTrade;
   public static Item itemFocusExcavation;
   public static Item itemFocusHellbat;
   public static Item itemFocusWarding;
   public static Item itemFocusPrimal;
   public static Item itemEssence;
   public static Item itemWispEssence;
   public static Item itemCrystalEssence;
   public static Item itemResource;
   public static Item itemShard;
   public static Item itemNugget;
   public static Item itemNuggetChicken;
   public static Item itemNuggetBeef;
   public static Item itemNuggetPork;
   public static Item itemNuggetFish;
   public static Item itemTripleMeatTreat;
   public static Item itemPhotoPlate;
   public static Item itemManaBean;
   public static Item itemZombieBrain;
   public static Item itemResearchNotes;
   public static Item itemInkwell;
   public static Item itemThaumonomicon;
   public static Item itemSpawnerEgg;
   public static Item itemFocusPortableHole;
   public static Item itemFocusPech;
   public static Item itemThaumometer;
   public static Item itemFlyingCarpet;
   public static Item itemGolemPlacer;
   public static Item itemGolemBell;
   public static Item itemGolemDecoration;
   public static Item itemGolemCore;
   public static Item itemGolemUpgrade;
   public static Item itemArcaneDoor;
   public static Item itemJarFilled;
   public static Item itemJarNode;
   public static Item itemKey;
   public static Item itemHandMirror;
   public static Item itemTrunkSpawner;
   public static Item itemResonator;
   public static Item itemBathSalts;
   public static Item itemBucketDeath;
   public static Item itemBucketPure;
   public static Item itemEldritchObject;
   public static Item itemSanitySoap;
   public static Item itemSanityChecker;
   public static Item itemBottleTaint;
   public static Item itemGoggles;
   public static Item itemBootsTraveller;
   public static Item itemHelmetThaumium;
   public static Item itemChestThaumium;
   public static Item itemBootsThaumium;
   public static Item itemLegsThaumium;
   public static Item itemShovelThaumium;
   public static Item itemShovelElemental;
   public static Item itemPickThaumium;
   public static Item itemPickElemental;
   public static Item itemSwordThaumium;
   public static Item itemSwordElemental;
   public static Item itemAxeThaumium;
   public static Item itemAxeElemental;
   public static Item itemHoeThaumium;
   public static Item itemHoeElemental;
   public static Item itemHelmetFortress;
   public static Item itemChestFortress;
   public static Item itemBootsFortress;
   public static Item itemLegsFortress;
   public static Item itemHelmetVoid;
   public static Item itemChestVoid;
   public static Item itemBootsVoid;
   public static Item itemLegsVoid;
   public static Item itemShovelVoid;
   public static Item itemPickVoid;
   public static Item itemSwordVoid;
   public static Item itemSwordCrimson;
   public static Item itemAxeVoid;
   public static Item itemHoeVoid;
   public static Item itemHelmetVoidRobe;
   public static Item itemChestVoidRobe;
   public static Item itemLegsVoidRobe;
   public static Item itemHelmetCultistRobe;
   public static Item itemChestCultistRobe;
   public static Item itemLegsCultistRobe;
   public static Item itemBootsCultist;
   public static Item itemHelmetCultistPlate;
   public static Item itemChestCultistPlate;
   public static Item itemLegsCultistPlate;
   public static Item itemHelmetCultistLeaderPlate;
   public static Item itemChestCultistLeaderPlate;
   public static Item itemLegsCultistLeaderPlate;
   public static Item itemLootbag;
   public static Item itemBaubleBlanks;
   public static Item itemAmuletRunic;
   public static Item itemRingRunic;
   public static Item itemGirdleRunic;
   public static Item itemGirdleHover;
   public static Item itemAmuletVis;
   public static Item itemLegsRobe;
   public static Item itemChestRobe;
   public static Item itemBootsRobe;
   public static Item itemHoverHarness;
   public static Item itemBowBone;
   public static Item itemPrimalArrow;
   public static Item itemCompassStone;
   public static Item itemPrimalCrusher;

   public static void init() {
      initializeItems();
      OreDictionary.registerOre("oreCinnabar", new ItemStack(ConfigBlocks.blockCustomOre, 1, 0));
      OreDictionary.registerOre("oreInfusedAir", new ItemStack(ConfigBlocks.blockCustomOre, 1, 1));
      OreDictionary.registerOre("oreInfusedFire", new ItemStack(ConfigBlocks.blockCustomOre, 1, 2));
      OreDictionary.registerOre("oreInfusedWater", new ItemStack(ConfigBlocks.blockCustomOre, 1, 3));
      OreDictionary.registerOre("oreInfusedEarth", new ItemStack(ConfigBlocks.blockCustomOre, 1, 4));
      OreDictionary.registerOre("oreInfusedOrder", new ItemStack(ConfigBlocks.blockCustomOre, 1, 5));
      OreDictionary.registerOre("oreInfusedEntropy", new ItemStack(ConfigBlocks.blockCustomOre, 1, 6));
      OreDictionary.registerOre("shardAir", new ItemStack(itemShard, 1, 0));
      OreDictionary.registerOre("shardFire", new ItemStack(itemShard, 1, 1));
      OreDictionary.registerOre("shardWater", new ItemStack(itemShard, 1, 2));
      OreDictionary.registerOre("shardEarth", new ItemStack(itemShard, 1, 3));
      OreDictionary.registerOre("shardOrder", new ItemStack(itemShard, 1, 4));
      OreDictionary.registerOre("shardEntropy", new ItemStack(itemShard, 1, 5));
      OreDictionary.registerOre("oreAmber", new ItemStack(ConfigBlocks.blockCustomOre, 1, 7));
      OreDictionary.registerOre("quicksilver", new ItemStack(itemResource, 1, 3));
      OreDictionary.registerOre("gemAmber", new ItemStack(itemResource, 1, 6));
      OreDictionary.registerOre("nuggetIron", new ItemStack(itemNugget, 1, 0));
      OreDictionary.registerOre("nuggetCopper", new ItemStack(itemNugget, 1, 1));
      OreDictionary.registerOre("nuggetTin", new ItemStack(itemNugget, 1, 2));
      OreDictionary.registerOre("nuggetSilver", new ItemStack(itemNugget, 1, 3));
      OreDictionary.registerOre("nuggetLead", new ItemStack(itemNugget, 1, 4));
      OreDictionary.registerOre("nuggetThaumium", new ItemStack(itemNugget, 1, 6));
      OreDictionary.registerOre("nuggetVoid", new ItemStack(itemNugget, 1, 7));
      OreDictionary.registerOre("nuggetQuicksilver", new ItemStack(itemResource, 1, 3));
      OreDictionary.registerOre("nuggetGold", new ItemStack(itemResource, 1, 18));
      OreDictionary.registerOre("ingotThaumium", new ItemStack(itemResource, 1, 2));
      OreDictionary.registerOre("ingotVoid", new ItemStack(itemResource, 1, 16));
      OreDictionary.registerOre("clusterIron", new ItemStack(itemNugget, 1, 16));
      OreDictionary.registerOre("clusterCopper", new ItemStack(itemNugget, 1, 17));
      OreDictionary.registerOre("clusterTin", new ItemStack(itemNugget, 1, 18));
      OreDictionary.registerOre("clusterSilver", new ItemStack(itemNugget, 1, 19));
      OreDictionary.registerOre("clusterLead", new ItemStack(itemNugget, 1, 20));
      OreDictionary.registerOre("clusterCinnabar", new ItemStack(itemNugget, 1, 21));
      OreDictionary.registerOre("clusterGold", new ItemStack(itemNugget, 1, 31));
      OreDictionary.registerOre("logWood", new ItemStack(ConfigBlocks.blockMagicalLog, 1, 0));
      OreDictionary.registerOre("logWood", new ItemStack(ConfigBlocks.blockMagicalLog, 1, 1));
      OreDictionary.registerOre("plankWood", new ItemStack(ConfigBlocks.blockWoodenDevice, 1, 6));
      OreDictionary.registerOre("plankWood", new ItemStack(ConfigBlocks.blockWoodenDevice, 1, 7));
      OreDictionary.registerOre("slabWood", new ItemStack(ConfigBlocks.blockSlabWood, 1, 0));
      OreDictionary.registerOre("slabWood", new ItemStack(ConfigBlocks.blockSlabWood, 1, 1));
      OreDictionary.registerOre("treeSapling", new ItemStack(ConfigBlocks.blockCustomPlant, 1, 0));
      OreDictionary.registerOre("treeSapling", new ItemStack(ConfigBlocks.blockCustomPlant, 1, 1));
      WAND_CAP_IRON = new WandCap("iron", 1.1F, new ItemStack(itemWandCap, 1, 0), 1);
      WAND_CAP_GOLD = new WandCap("gold", 1.0F, new ItemStack(itemWandCap, 1, 1), 3);
      WAND_CAP_THAUMIUM = new WandCap("thaumium", 0.9F, new ItemStack(itemWandCap, 1, 2), 6);
      WAND_CAP_VOID = new WandCap("void", 0.8F, new ItemStack(itemWandCap, 1, 7), 9);
      WAND_ROD_WOOD = new WandRod("wood", 25, new ItemStack(Items.STICK), 1);
      WAND_ROD_GREATWOOD = new WandRod("greatwood", 50, new ItemStack(itemWandRod, 1, 0), 3);
      WAND_ROD_OBSIDIAN = new WandRod("obsidian", 75, new ItemStack(itemWandRod, 1, 1), 6, new WandRodPrimalOnUpdate(Aspect.EARTH));
      WAND_ROD_BLAZE = new WandRod("blaze", 75, new ItemStack(itemWandRod, 1, 6), 6, new WandRodPrimalOnUpdate(Aspect.FIRE));
      WAND_ROD_ICE = new WandRod("ice", 75, new ItemStack(itemWandRod, 1, 3), 6, new WandRodPrimalOnUpdate(Aspect.WATER));
      WAND_ROD_QUARTZ = new WandRod("quartz", 75, new ItemStack(itemWandRod, 1, 4), 6, new WandRodPrimalOnUpdate(Aspect.ORDER));
      WAND_ROD_BONE = new WandRod("bone", 75, new ItemStack(itemWandRod, 1, 7), 6, new WandRodPrimalOnUpdate(Aspect.ENTROPY));
      WAND_ROD_REED = new WandRod("reed", 75, new ItemStack(itemWandRod, 1, 5), 6, new WandRodPrimalOnUpdate(Aspect.AIR));
      WAND_ROD_SILVERWOOD = new WandRod("silverwood", 100, new ItemStack(itemWandRod, 1, 2), 9);
      WAND_ROD_BLAZE.setGlowing(true);
      STAFF_ROD_GREATWOOD = new StaffRod("greatwood", 125, new ItemStack(itemWandRod, 1, 50), 8);
      STAFF_ROD_OBSIDIAN = new StaffRod("obsidian", 175, new ItemStack(itemWandRod, 1, 51), 14, new WandRodPrimalOnUpdate(Aspect.EARTH));
      STAFF_ROD_BLAZE = new StaffRod("blaze", 175, new ItemStack(itemWandRod, 1, 56), 14, new WandRodPrimalOnUpdate(Aspect.FIRE));
      STAFF_ROD_ICE = new StaffRod("ice", 175, new ItemStack(itemWandRod, 1, 53), 14, new WandRodPrimalOnUpdate(Aspect.WATER));
      STAFF_ROD_QUARTZ = new StaffRod("quartz", 175, new ItemStack(itemWandRod, 1, 54), 14, new WandRodPrimalOnUpdate(Aspect.ORDER));
      STAFF_ROD_BONE = new StaffRod("bone", 175, new ItemStack(itemWandRod, 1, 57), 14, new WandRodPrimalOnUpdate(Aspect.ENTROPY));
      STAFF_ROD_REED = new StaffRod("reed", 175, new ItemStack(itemWandRod, 1, 55), 14, new WandRodPrimalOnUpdate(Aspect.AIR));
      STAFF_ROD_SILVERWOOD = new StaffRod("silverwood", 250, new ItemStack(itemWandRod, 1, 52), 24);
      STAFF_ROD_PRIMAL = new StaffRod("primal", 250, new ItemStack(itemWandRod, 1, 100), 32, new WandRodPrimalOnUpdate());
      STAFF_ROD_PRIMAL.setRunes(true);
      STAFF_ROD_BLAZE.setGlowing(true);
   }

   public static void postInit() {
      if (Config.foundCopperIngot) {
         WAND_CAP_COPPER = new WandCap("copper", 1.1F, Arrays.asList(Aspect.ORDER, Aspect.ENTROPY), 1.0F, new ItemStack(itemWandCap, 1, 3), 2);
      }

      if (Config.foundSilverIngot) {
         WAND_CAP_SILVER = new WandCap("silver", 1.0F, Arrays.asList(Aspect.AIR, Aspect.EARTH, Aspect.FIRE, Aspect.WATER), 0.95F, new ItemStack(itemWandCap, 1, 4), 4);
      }

   }

   private static void initializeItems() {
      itemWandCasting = (new ItemWandCasting()).setTranslationKey("WandCasting");
      ForgeRegistries.ITEMS.register(itemWandCasting.setRegistryName("thaumcraft", "wandcasting"));
      itemWandCap = (new ItemWandCap()).setTranslationKey("WandCap");
      ForgeRegistries.ITEMS.register(itemWandCap.setRegistryName("thaumcraft", "wandcap"));
      itemWandRod = (new ItemWandRod()).setTranslationKey("WandRod");
      ForgeRegistries.ITEMS.register(itemWandRod.setRegistryName("thaumcraft", "wandrod"));
      itemFocusPouch = (new ItemFocusPouchBauble()).setTranslationKey("FocusPouch");
      ForgeRegistries.ITEMS.register(itemFocusPouch.setRegistryName("thaumcraft", "focuspouch"));
      itemFocusFire = (new ItemFocusFire()).setTranslationKey("FocusFire");
      ForgeRegistries.ITEMS.register(itemFocusFire.setRegistryName("thaumcraft", "focusfire"));
      itemFocusShock = (new ItemFocusShock()).setTranslationKey("FocusShock");
      ForgeRegistries.ITEMS.register(itemFocusShock.setRegistryName("thaumcraft", "focusshock"));
      itemFocusHellbat = (new ItemFocusHellbat()).setTranslationKey("FocusHellbat");
      ForgeRegistries.ITEMS.register(itemFocusHellbat.setRegistryName("thaumcraft", "focushellbat"));
      itemFocusFrost = (new ItemFocusFrost()).setTranslationKey("FocusFrost");
      ForgeRegistries.ITEMS.register(itemFocusFrost.setRegistryName("thaumcraft", "focusfrost"));
      itemFocusTrade = (new ItemFocusTrade()).setTranslationKey("FocusTrade");
      ForgeRegistries.ITEMS.register(itemFocusTrade.setRegistryName("thaumcraft", "focustrade"));
      itemFocusExcavation = (new ItemFocusExcavation()).setTranslationKey("FocusExcavation");
      ForgeRegistries.ITEMS.register(itemFocusExcavation.setRegistryName("thaumcraft", "focusexcavation"));
      itemFocusPortableHole = (new ItemFocusPortableHole()).setTranslationKey("FocusPortableHole");
      ForgeRegistries.ITEMS.register(itemFocusPortableHole.setRegistryName("thaumcraft", "focusportablehole"));
      itemFocusPech = (new ItemFocusPech()).setTranslationKey("FocusPech");
      ForgeRegistries.ITEMS.register(itemFocusPech.setRegistryName("thaumcraft", "focuspech"));
      itemFocusWarding = (new ItemFocusWarding()).setTranslationKey("FocusWarding");
      ForgeRegistries.ITEMS.register(itemFocusWarding.setRegistryName("thaumcraft", "focuswarding"));
      itemFocusPrimal = (new ItemFocusPrimal()).setTranslationKey("FocusPrimal");
      ForgeRegistries.ITEMS.register(itemFocusPrimal.setRegistryName("thaumcraft", "focusprimal"));
      itemEssence = (new ItemEssence()).setTranslationKey("ItemEssence");
      ForgeRegistries.ITEMS.register(itemEssence.setRegistryName("thaumcraft", "itemessence"));
      itemManaBean = (new ItemManaBean()).setTranslationKey("ItemManaBean");
      ForgeRegistries.ITEMS.register(itemManaBean.setRegistryName("thaumcraft", "itemmanabean"));
      itemWispEssence = (new ItemWispEssence()).setTranslationKey("ItemWispEssence");
      ForgeRegistries.ITEMS.register(itemWispEssence.setRegistryName("thaumcraft", "itemwispessence"));
      itemResource = (new ItemResource()).setTranslationKey("ItemResource");
      ForgeRegistries.ITEMS.register(itemResource.setRegistryName("thaumcraft", "itemresource"));
      itemShard = (new ItemShard()).setTranslationKey("ItemShard");
      ForgeRegistries.ITEMS.register(itemShard.setRegistryName("thaumcraft", "itemshard"));
      itemResearchNotes = (new ItemResearchNotes()).setTranslationKey("ItemResearchNotes");
      ForgeRegistries.ITEMS.register(itemResearchNotes.setRegistryName("thaumcraft", "itemresearchnotes"));
      itemInkwell = (new ItemInkwell()).setTranslationKey("ItemInkwell");
      ForgeRegistries.ITEMS.register(itemInkwell.setRegistryName("thaumcraft", "iteminkwell"));
      itemThaumonomicon = (new ItemThaumonomicon()).setTranslationKey("ItemThaumonomicon");
      ForgeRegistries.ITEMS.register(itemThaumonomicon.setRegistryName("thaumcraft", "itemthaumonomicon"));
      itemThaumometer = (new ItemThaumometer()).setTranslationKey("ItemThaumometer");
      ForgeRegistries.ITEMS.register(itemThaumometer.setRegistryName("thaumcraft", "itemthaumometer"));
      itemGoggles = (new ItemGoggles(ThaumcraftApi.armorMatSpecial, 4, 0)).setTranslationKey("ItemGoggles");
      ForgeRegistries.ITEMS.register(itemGoggles.setRegistryName("thaumcraft", "itemgoggles"));
      itemHelmetThaumium = (new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 0)).setTranslationKey("ItemHelmetThaumium");
      ForgeRegistries.ITEMS.register(itemHelmetThaumium.setRegistryName("thaumcraft", "itemhelmetthaumium"));
      itemChestThaumium = (new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 1)).setTranslationKey("ItemChestplateThaumium");
      ForgeRegistries.ITEMS.register(itemChestThaumium.setRegistryName("thaumcraft", "itemchestplatethaumium"));
      itemLegsThaumium = (new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 2)).setTranslationKey("ItemLeggingsThaumium");
      ForgeRegistries.ITEMS.register(itemLegsThaumium.setRegistryName("thaumcraft", "itemleggingsthaumium"));
      itemBootsThaumium = (new ItemThaumiumArmor(ThaumcraftApi.armorMatThaumium, 2, 3)).setTranslationKey("ItemBootsThaumium");
      ForgeRegistries.ITEMS.register(itemBootsThaumium.setRegistryName("thaumcraft", "itembootsthaumium"));
      itemShovelThaumium = (new ItemThaumiumShovel(ThaumcraftApi.toolMatThaumium)).setTranslationKey("ItemShovelThaumium");
      ForgeRegistries.ITEMS.register(itemShovelThaumium.setRegistryName("thaumcraft", "itemshovelthaumium"));
      itemPickThaumium = (new ItemThaumiumPickaxe(ThaumcraftApi.toolMatThaumium)).setTranslationKey("ItemPickThaumium");
      ForgeRegistries.ITEMS.register(itemPickThaumium.setRegistryName("thaumcraft", "itempickthaumium"));
      itemAxeThaumium = (new ItemThaumiumAxe(ThaumcraftApi.toolMatThaumium)).setTranslationKey("ItemAxeThaumium");
      ForgeRegistries.ITEMS.register(itemAxeThaumium.setRegistryName("thaumcraft", "itemaxethaumium"));
      itemSwordThaumium = (new ItemThaumiumSword(ThaumcraftApi.toolMatThaumium)).setTranslationKey("ItemSwordThaumium");
      ForgeRegistries.ITEMS.register(itemSwordThaumium.setRegistryName("thaumcraft", "itemswordthaumium"));
      itemHoeThaumium = (new ItemThaumiumHoe(ThaumcraftApi.toolMatThaumium)).setTranslationKey("ItemHoeThaumium");
      ForgeRegistries.ITEMS.register(itemHoeThaumium.setRegistryName("thaumcraft", "itemhoethaumium"));
      itemArcaneDoor = (new ItemArcaneDoor()).setTranslationKey("ItemArcaneDoor");
      ForgeRegistries.ITEMS.register(itemArcaneDoor.setRegistryName("thaumcraft", "itemarcanedoor"));
      itemNugget = (new ItemNugget()).setTranslationKey("ItemNugget");
      ForgeRegistries.ITEMS.register(itemNugget.setRegistryName("thaumcraft", "itemnugget"));
      itemBootsTraveller = (new ItemBootsTraveller(ThaumcraftApi.armorMatSpecial, 4, 3)).setTranslationKey("BootsTraveller");
      ForgeRegistries.ITEMS.register(itemBootsTraveller.setRegistryName("thaumcraft", "bootstraveller"));
      itemNuggetChicken = (new ItemNuggetEdible("nuggetchicken")).setTranslationKey("ItemNuggetChicken");
      ForgeRegistries.ITEMS.register(itemNuggetChicken.setRegistryName("thaumcraft", "itemnuggetchicken"));
      itemNuggetBeef = (new ItemNuggetEdible("nuggetbeef")).setTranslationKey("ItemNuggetBeef");
      ForgeRegistries.ITEMS.register(itemNuggetBeef.setRegistryName("thaumcraft", "itemnuggetbeef"));
      itemNuggetPork = (new ItemNuggetEdible("nuggetpork")).setTranslationKey("ItemNuggetPork");
      ForgeRegistries.ITEMS.register(itemNuggetPork.setRegistryName("thaumcraft", "itemnuggetpork"));
      itemNuggetFish = (new ItemNuggetEdible("nuggetfish")).setTranslationKey("ItemNuggetFish");
      ForgeRegistries.ITEMS.register(itemNuggetFish.setRegistryName("thaumcraft", "itemnuggetfish"));
      itemTripleMeatTreat = (new ItemTripleMeatTreat()).setTranslationKey("TripleMeatTreat");
      ForgeRegistries.ITEMS.register(itemTripleMeatTreat.setRegistryName("thaumcraft", "triplemeattreat"));
      itemSwordElemental = (new ItemElementalSword(ThaumcraftApi.toolMatElemental)).setTranslationKey("ItemSwordElemental");
      ForgeRegistries.ITEMS.register(itemSwordElemental.setRegistryName("thaumcraft", "itemswordelemental"));
      itemShovelElemental = (new ItemElementalShovel(ThaumcraftApi.toolMatElemental)).setTranslationKey("ItemShovelElemental");
      ForgeRegistries.ITEMS.register(itemShovelElemental.setRegistryName("thaumcraft", "itemshovelelemental"));
      itemPickElemental = (new ItemElementalPickaxe(ThaumcraftApi.toolMatElemental)).setTranslationKey("ItemPickaxeElemental");
      ForgeRegistries.ITEMS.register(itemPickElemental.setRegistryName("thaumcraft", "itempickaxeelemental"));
      itemAxeElemental = (new ItemElementalAxe(ThaumcraftApi.toolMatElemental)).setTranslationKey("ItemAxeElemental");
      ForgeRegistries.ITEMS.register(itemAxeElemental.setRegistryName("thaumcraft", "itemaxeelemental"));
      itemHoeElemental = (new ItemElementalHoe(ThaumcraftApi.toolMatElemental)).setTranslationKey("ItemHoeElemental");
      ForgeRegistries.ITEMS.register(itemHoeElemental.setRegistryName("thaumcraft", "itemhoeelemental"));
      itemChestRobe = (new ItemRobeArmor(ThaumcraftApi.armorMatSpecial, 1, 1)).setTranslationKey("ItemChestplateRobe");
      ForgeRegistries.ITEMS.register(itemChestRobe.setRegistryName("thaumcraft", "itemchestplaterobe"));
      itemLegsRobe = (new ItemRobeArmor(ThaumcraftApi.armorMatSpecial, 2, 2)).setTranslationKey("ItemLeggingsRobe");
      ForgeRegistries.ITEMS.register(itemLegsRobe.setRegistryName("thaumcraft", "itemleggingsrobe"));
      itemBootsRobe = (new ItemRobeArmor(ThaumcraftApi.armorMatSpecial, 1, 3)).setTranslationKey("ItemBootsRobe");
      ForgeRegistries.ITEMS.register(itemBootsRobe.setRegistryName("thaumcraft", "itembootsrobe"));
      itemKey = (new ItemKey()).setTranslationKey("ArcaneDoorKey");
      ForgeRegistries.ITEMS.register(itemKey.setRegistryName("thaumcraft", "arcanedoorkey"));
      itemHandMirror = (new ItemHandMirror()).setTranslationKey("HandMirror");
      ForgeRegistries.ITEMS.register(itemHandMirror.setRegistryName("thaumcraft", "handmirror"));
      itemHoverHarness = (new ItemHoverHarness(ThaumcraftApi.armorMatSpecial, 1, 1)).setTranslationKey("HoverHarness");
      ForgeRegistries.ITEMS.register(itemHoverHarness.setRegistryName("thaumcraft", "hoverharness"));
      itemJarFilled = (new ItemJarFilled()).setTranslationKey("BlockJarFilledItem");
      ForgeRegistries.ITEMS.register(itemJarFilled.setRegistryName("thaumcraft", "blockjarfilleditem"));
      itemJarNode = (new ItemJarNode()).setTranslationKey("BlockJarNodeItem");
      ForgeRegistries.ITEMS.register(itemJarNode.setRegistryName("thaumcraft", "blockjarnodeitem"));
      itemTrunkSpawner = (new ItemTrunkSpawner()).setTranslationKey("TrunkSpawner");
      ForgeRegistries.ITEMS.register(itemTrunkSpawner.setRegistryName("thaumcraft", "trunkspawner"));
      itemGolemPlacer = (new ItemGolemPlacer()).setTranslationKey("ItemGolemPlacer");
      ForgeRegistries.ITEMS.register(itemGolemPlacer.setRegistryName("thaumcraft", "itemgolemplacer"));
      itemGolemCore = (new ItemGolemCore()).setTranslationKey("ItemGolemCore");
      ForgeRegistries.ITEMS.register(itemGolemCore.setRegistryName("thaumcraft", "itemgolemcore"));
      itemGolemUpgrade = (new ItemGolemUpgrade()).setTranslationKey("ItemGolemUpgrade");
      ForgeRegistries.ITEMS.register(itemGolemUpgrade.setRegistryName("thaumcraft", "itemgolemupgrade"));
      itemGolemBell = (new ItemGolemBell()).setTranslationKey("GolemBell");
      ForgeRegistries.ITEMS.register(itemGolemBell.setRegistryName("thaumcraft", "golembell"));
      itemGolemDecoration = (new ItemGolemDecoration()).setTranslationKey("ItemGolemDecoration");
      ForgeRegistries.ITEMS.register(itemGolemDecoration.setRegistryName("thaumcraft", "itemgolemdecoration"));
      itemBowBone = (new ItemBowBone()).setTranslationKey("ItemBowBone");
      ForgeRegistries.ITEMS.register(itemBowBone.setRegistryName("thaumcraft", "itembowbone"));
      itemPrimalArrow = (new ItemPrimalArrow()).setTranslationKey("ItemPrimalArrow");
      ForgeRegistries.ITEMS.register(itemPrimalArrow.setRegistryName("thaumcraft", "primalarrow"));
      itemResonator = (new ItemResonator()).setTranslationKey("ItemResonator");
      ForgeRegistries.ITEMS.register(itemResonator.setRegistryName("thaumcraft", "itemresonator"));
      itemBaubleBlanks = (new ItemBaubleBlanks()).setTranslationKey("ItemBaubleBlanks");
      ForgeRegistries.ITEMS.register(itemBaubleBlanks.setRegistryName("thaumcraft", "itembaubleblanks"));
      itemAmuletRunic = (new ItemAmuletRunic()).setTranslationKey("ItemAmuletRunic");
      ForgeRegistries.ITEMS.register(itemAmuletRunic.setRegistryName("thaumcraft", "itemamuletrunic"));
      itemRingRunic = (new ItemRingRunic()).setTranslationKey("ItemRingRunic");
      ForgeRegistries.ITEMS.register(itemRingRunic.setRegistryName("thaumcraft", "itemringrunic"));
      itemGirdleRunic = (new ItemGirdleRunic()).setTranslationKey("ItemGirdleRunic");
      ForgeRegistries.ITEMS.register(itemGirdleRunic.setRegistryName("thaumcraft", "itemgirdlerunic"));
      itemAmuletVis = (new ItemAmuletVis()).setTranslationKey("ItemAmuletVis");
      ForgeRegistries.ITEMS.register(itemAmuletVis.setRegistryName("thaumcraft", "itemamuletvis"));
      itemGirdleHover = (new ItemGirdleHover()).setTranslationKey("ItemGirdleHover");
      ForgeRegistries.ITEMS.register(itemGirdleHover.setRegistryName("thaumcraft", "itemgirdlehover"));
      itemSpawnerEgg = (new ItemSpawnerEgg()).setTranslationKey("ItemSpawnerEgg");
      ForgeRegistries.ITEMS.register(itemSpawnerEgg.setRegistryName("thaumcraft", "itemspawneregg"));
      itemZombieBrain = (new ItemZombieBrain()).setTranslationKey("ItemZombieBrain");
      ForgeRegistries.ITEMS.register(itemZombieBrain.setRegistryName("thaumcraft", "itemzombiebrain"));
      itemBathSalts = (new ItemBathSalts()).setTranslationKey("ItemBathSalts");
      ForgeRegistries.ITEMS.register(itemBathSalts.setRegistryName("thaumcraft", "itembathsalts"));
      itemCrystalEssence = (new ItemCrystalEssence()).setTranslationKey("ItemCrystalEssence");
      ForgeRegistries.ITEMS.register(itemCrystalEssence.setRegistryName("thaumcraft", "itemcrystalessence"));
      itemBucketDeath = (new ItemBucketDeath()).setTranslationKey("ItemBucketDeath");
      ForgeRegistries.ITEMS.register(itemBucketDeath.setRegistryName("thaumcraft", "itembucketdeath"));
      itemBucketPure = (new ItemBucketPure()).setTranslationKey("ItemBucketPure");
      ForgeRegistries.ITEMS.register(itemBucketPure.setRegistryName("thaumcraft", "itembucketpure"));
      itemHelmetFortress = (new ItemFortressArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 0)).setTranslationKey("ItemHelmetFortress");
      ForgeRegistries.ITEMS.register(itemHelmetFortress.setRegistryName("thaumcraft", "itemhelmetfortress"));
      itemChestFortress = (new ItemFortressArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 1)).setTranslationKey("ItemChestplateFortress");
      ForgeRegistries.ITEMS.register(itemChestFortress.setRegistryName("thaumcraft", "itemchestplatefortress"));
      itemLegsFortress = (new ItemFortressArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 2)).setTranslationKey("ItemLeggingsFortress");
      ForgeRegistries.ITEMS.register(itemLegsFortress.setRegistryName("thaumcraft", "itemleggingsfortress"));
      itemEldritchObject = (new ItemEldritchObject()).setTranslationKey("ItemEldritchObject");
      ForgeRegistries.ITEMS.register(itemEldritchObject.setRegistryName("thaumcraft", "itemeldritchobject"));
      itemHelmetVoid = (new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 0)).setTranslationKey("ItemHelmetVoid");
      ForgeRegistries.ITEMS.register(itemHelmetVoid.setRegistryName("thaumcraft", "itemhelmetvoid"));
      itemChestVoid = (new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 1)).setTranslationKey("ItemChestplateVoid");
      ForgeRegistries.ITEMS.register(itemChestVoid.setRegistryName("thaumcraft", "itemchestplatevoid"));
      itemLegsVoid = (new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 2)).setTranslationKey("ItemLeggingsVoid");
      ForgeRegistries.ITEMS.register(itemLegsVoid.setRegistryName("thaumcraft", "itemleggingsvoid"));
      itemBootsVoid = (new ItemVoidArmor(ThaumcraftApi.armorMatVoid, 2, 3)).setTranslationKey("ItemBootsVoid");
      ForgeRegistries.ITEMS.register(itemBootsVoid.setRegistryName("thaumcraft", "itembootsvoid"));
      itemShovelVoid = (new ItemVoidShovel(ThaumcraftApi.toolMatVoid)).setTranslationKey("ItemShovelVoid");
      ForgeRegistries.ITEMS.register(itemShovelVoid.setRegistryName("thaumcraft", "itemshovelvoid"));
      itemPickVoid = (new ItemVoidPickaxe(ThaumcraftApi.toolMatVoid)).setTranslationKey("ItemPickVoid");
      ForgeRegistries.ITEMS.register(itemPickVoid.setRegistryName("thaumcraft", "itempickvoid"));
      itemAxeVoid = (new ItemVoidAxe(ThaumcraftApi.toolMatVoid)).setTranslationKey("ItemAxeVoid");
      ForgeRegistries.ITEMS.register(itemAxeVoid.setRegistryName("thaumcraft", "itemaxevoid"));
      itemSwordVoid = (new ItemVoidSword(ThaumcraftApi.toolMatVoid)).setTranslationKey("ItemSwordVoid");
      ForgeRegistries.ITEMS.register(itemSwordVoid.setRegistryName("thaumcraft", "itemswordvoid"));
      itemHoeVoid = (new ItemVoidHoe(ThaumcraftApi.toolMatVoid)).setTranslationKey("ItemHoeVoid");
      ForgeRegistries.ITEMS.register(itemHoeVoid.setRegistryName("thaumcraft", "itemhoevoid"));
      itemHelmetVoidRobe = (new ItemVoidRobeArmor(ThaumcraftApi.armorMatVoid, 4, 0)).setTranslationKey("ItemHelmetVoidRobe");
      ForgeRegistries.ITEMS.register(itemHelmetVoidRobe.setRegistryName("thaumcraft", "itemhelmetvoidfortress"));
      itemChestVoidRobe = (new ItemVoidRobeArmor(ThaumcraftApi.armorMatVoid, 4, 1)).setTranslationKey("ItemChestplateVoidRobe");
      ForgeRegistries.ITEMS.register(itemChestVoidRobe.setRegistryName("thaumcraft", "itemchestplatevoidfortress"));
      itemLegsVoidRobe = (new ItemVoidRobeArmor(ThaumcraftApi.armorMatVoid, 4, 2)).setTranslationKey("ItemLeggingsVoidRobe");
      ForgeRegistries.ITEMS.register(itemLegsVoidRobe.setRegistryName("thaumcraft", "itemleggingsvoidfortress"));
      itemSanitySoap = (new ItemSanitySoap()).setTranslationKey("ItemSanitySoap");
      ForgeRegistries.ITEMS.register(itemSanitySoap.setRegistryName("thaumcraft", "itemsanitysoap"));
      itemSanityChecker = (new ItemSanityChecker()).setTranslationKey("ItemSanityChecker");
      ForgeRegistries.ITEMS.register(itemSanityChecker.setRegistryName("thaumcraft", "itemsanitychecker"));
      itemBottleTaint = (new ItemBottleTaint()).setTranslationKey("ItemBottleTaint");
      ForgeRegistries.ITEMS.register(itemBottleTaint.setRegistryName("thaumcraft", "itembottletaint"));
      itemHelmetCultistRobe = (new ItemCultistRobeArmor(ArmorMaterial.IRON, 4, 0)).setTranslationKey("ItemHelmetCultistRobe");
      ForgeRegistries.ITEMS.register(itemHelmetCultistRobe.setRegistryName("thaumcraft", "itemhelmetcultistrobe"));
      itemChestCultistRobe = (new ItemCultistRobeArmor(ArmorMaterial.IRON, 4, 1)).setTranslationKey("ItemChestplateCultistRobe");
      ForgeRegistries.ITEMS.register(itemChestCultistRobe.setRegistryName("thaumcraft", "itemchestplatecultistrobe"));
      itemLegsCultistRobe = (new ItemCultistRobeArmor(ArmorMaterial.IRON, 4, 2)).setTranslationKey("ItemLeggingsCultistRobe");
      ForgeRegistries.ITEMS.register(itemLegsCultistRobe.setRegistryName("thaumcraft", "itemleggingscultistrobe"));
      itemBootsCultist = (new ItemCultistBoots(ArmorMaterial.IRON, 4, 3)).setTranslationKey("ItemBootsCultist");
      ForgeRegistries.ITEMS.register(itemBootsCultist.setRegistryName("thaumcraft", "itembootscultist"));
      itemHelmetCultistPlate = (new ItemCultistPlateArmor(ArmorMaterial.IRON, 4, 0)).setTranslationKey("ItemHelmetCultistPlate");
      ForgeRegistries.ITEMS.register(itemHelmetCultistPlate.setRegistryName("thaumcraft", "itemhelmetcultistplate"));
      itemChestCultistPlate = (new ItemCultistPlateArmor(ArmorMaterial.IRON, 4, 1)).setTranslationKey("ItemChestplateCultistPlate");
      ForgeRegistries.ITEMS.register(itemChestCultistPlate.setRegistryName("thaumcraft", "itemchestplatecultistplate"));
      itemLegsCultistPlate = (new ItemCultistPlateArmor(ArmorMaterial.IRON, 4, 2)).setTranslationKey("ItemLeggingsCultistPlate");
      ForgeRegistries.ITEMS.register(itemLegsCultistPlate.setRegistryName("thaumcraft", "itemleggingscultistplate"));
      itemHelmetCultistLeaderPlate = (new ItemCultistLeaderArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 0)).setTranslationKey("ItemHelmetCultistLeaderPlate");
      ForgeRegistries.ITEMS.register(itemHelmetCultistLeaderPlate.setRegistryName("thaumcraft", "itemhelmetcultistleaderplate"));
      itemChestCultistLeaderPlate = (new ItemCultistLeaderArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 1)).setTranslationKey("ItemChestplateCultistLeaderPlate");
      ForgeRegistries.ITEMS.register(itemChestCultistLeaderPlate.setRegistryName("thaumcraft", "itemchestplatecultistleaderplate"));
      itemLegsCultistLeaderPlate = (new ItemCultistLeaderArmor(ThaumcraftApi.armorMatThaumiumFortress, 4, 2)).setTranslationKey("ItemLeggingsCultistLeaderPlate");
      ForgeRegistries.ITEMS.register(itemLegsCultistLeaderPlate.setRegistryName("thaumcraft", "itemleggingscultistleaderplate"));
      itemSwordCrimson = (new ItemCrimsonSword()).setTranslationKey("ItemSwordCrimson");
      ForgeRegistries.ITEMS.register(itemSwordCrimson.setRegistryName("thaumcraft", "itemswordcrimson"));
      itemLootbag = (new ItemLootBag()).setTranslationKey("ItemLootBag");
      ForgeRegistries.ITEMS.register(itemLootbag.setRegistryName("thaumcraft", "itemlootbag"));
      itemCompassStone = (new ItemCompassStone()).setTranslationKey("ItemCompassStone");
      ForgeRegistries.ITEMS.register(itemCompassStone.setRegistryName("thaumcraft", "itemcompassstone"));
      itemPrimalCrusher = (new ItemPrimalCrusher(ItemPrimalCrusher.material)).setTranslationKey("ItemPrimalCrusher");
      ForgeRegistries.ITEMS.register(itemPrimalCrusher.setRegistryName("thaumcraft", "itemprimalcrusher"));
   }
}
