package thaumcraft.common.config;

import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumRarity;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.common.blocks.BlockAiry;
import thaumcraft.common.blocks.BlockAiryItem;
import thaumcraft.common.blocks.BlockAlchemyFurnace;
import thaumcraft.common.blocks.BlockArcaneDoor;
import thaumcraft.common.blocks.BlockArcaneFurnace;
import thaumcraft.common.blocks.BlockCandle;
import thaumcraft.common.blocks.BlockCandleItem;
import thaumcraft.common.blocks.BlockChestHungry;
import thaumcraft.common.blocks.BlockCosmeticOpaque;
import thaumcraft.common.blocks.BlockCosmeticOpaqueItem;
import thaumcraft.common.blocks.BlockCosmeticSolid;
import thaumcraft.common.blocks.BlockCosmeticSolidItem;
import thaumcraft.common.blocks.BlockCosmeticStairs;
import thaumcraft.common.blocks.BlockCosmeticStoneSlab;
import thaumcraft.common.blocks.BlockCosmeticStoneSlabItem;
import thaumcraft.common.blocks.BlockCosmeticWoodSlab;
import thaumcraft.common.blocks.BlockCosmeticWoodSlabItem;
import thaumcraft.common.blocks.BlockCrystal;
import thaumcraft.common.blocks.BlockCrystalItem;
import thaumcraft.common.blocks.BlockCustomOre;
import thaumcraft.common.blocks.BlockCustomOreItem;
import thaumcraft.common.blocks.BlockCustomPlant;
import thaumcraft.common.blocks.BlockCustomPlantItem;
import thaumcraft.common.blocks.BlockEldritch;
import thaumcraft.common.blocks.BlockEldritchItem;
import thaumcraft.common.blocks.BlockEldritchNothing;
import thaumcraft.common.blocks.BlockEldritchPortal;
import thaumcraft.common.blocks.BlockEssentiaReservoir;
import thaumcraft.common.blocks.BlockEssentiaReservoirItem;
import thaumcraft.common.blocks.BlockFluidDeath;
import thaumcraft.common.blocks.BlockFluidPure;
import thaumcraft.common.blocks.BlockFluxGas;
import thaumcraft.common.blocks.BlockFluxGasItem;
import thaumcraft.common.blocks.BlockFluxGoo;
import thaumcraft.common.blocks.BlockFluxGooItem;
import thaumcraft.common.blocks.BlockHole;
import thaumcraft.common.blocks.BlockJar;
import thaumcraft.common.blocks.BlockJarItem;
import thaumcraft.common.blocks.BlockLifter;
import thaumcraft.common.blocks.BlockLoot;
import thaumcraft.common.blocks.BlockLootItem;
import thaumcraft.common.blocks.BlockMagicBox;
import thaumcraft.common.blocks.BlockMagicalLeaves;
import thaumcraft.common.blocks.BlockMagicalLeavesItem;
import thaumcraft.common.blocks.BlockMagicalLog;
import thaumcraft.common.blocks.BlockMagicalLogItem;
import thaumcraft.common.blocks.BlockManaPod;
import thaumcraft.common.blocks.BlockMetalDevice;
import thaumcraft.common.blocks.BlockMetalDeviceItem;
import thaumcraft.common.blocks.BlockMirror;
import thaumcraft.common.blocks.BlockMirrorItem;
import thaumcraft.common.blocks.BlockStoneDevice;
import thaumcraft.common.blocks.BlockStoneDeviceItem;
import thaumcraft.common.blocks.BlockTable;
import thaumcraft.common.blocks.BlockTableItem;
import thaumcraft.common.blocks.BlockTaint;
import thaumcraft.common.blocks.BlockTaintFibres;
import thaumcraft.common.blocks.BlockTaintFibresItem;
import thaumcraft.common.blocks.BlockTaintItem;
import thaumcraft.common.blocks.BlockTube;
import thaumcraft.common.blocks.BlockTubeItem;
import thaumcraft.common.blocks.BlockWarded;
import thaumcraft.common.blocks.BlockWoodenDevice;
import thaumcraft.common.blocks.BlockWoodenDeviceItem;
import thaumcraft.common.blocks.CustomStepSound;
import thaumcraft.common.tiles.TileAlchemyFurnace;
import thaumcraft.common.tiles.TileAlchemyFurnaceAdvanced;
import thaumcraft.common.tiles.TileAlchemyFurnaceAdvancedNozzle;
import thaumcraft.common.tiles.TileAlembic;
import thaumcraft.common.tiles.TileArcaneBore;
import thaumcraft.common.tiles.TileArcaneBoreBase;
import thaumcraft.common.tiles.TileArcaneFurnace;
import thaumcraft.common.tiles.TileArcaneFurnaceNozzle;
import thaumcraft.common.tiles.TileArcaneLamp;
import thaumcraft.common.tiles.TileArcaneLampLight;
import thaumcraft.common.tiles.TileArcaneLampFertility;
import thaumcraft.common.tiles.TileArcaneLampGrowth;
import thaumcraft.common.tiles.TileArcanePressurePlate;
import thaumcraft.common.tiles.TileArcaneWorkbench;
import thaumcraft.common.tiles.TileBanner;
import thaumcraft.common.tiles.TileBellows;
import thaumcraft.common.tiles.TileBrainbox;
import thaumcraft.common.tiles.TileCentrifuge;
import thaumcraft.common.tiles.TileChestHungry;
import thaumcraft.common.tiles.TileCrucible;
import thaumcraft.common.tiles.TileCrystal;
import thaumcraft.common.tiles.TileDeconstructionTable;
import thaumcraft.common.tiles.TileEldritchAltar;
import thaumcraft.common.tiles.TileEldritchCap;
import thaumcraft.common.tiles.TileEldritchCrabSpawner;
import thaumcraft.common.tiles.TileEldritchCrystal;
import thaumcraft.common.tiles.TileEldritchLock;
import thaumcraft.common.tiles.TileEldritchNothing;
import thaumcraft.common.tiles.TileEldritchObelisk;
import thaumcraft.common.tiles.TileEldritchPortal;
import thaumcraft.common.tiles.TileEldritchStone;
import thaumcraft.common.tiles.TileEldritchTrap;
import thaumcraft.common.tiles.TileEssentiaCrystalizer;
import thaumcraft.common.tiles.TileEssentiaReservoir;
import thaumcraft.common.tiles.TileEtherealBloom;
import thaumcraft.common.tiles.TileFluxScrubber;
import thaumcraft.common.tiles.TileFocalManipulator;
import thaumcraft.common.tiles.TileGrate;
import thaumcraft.common.tiles.TileHole;
import thaumcraft.common.tiles.TileInfusionMatrix;
import thaumcraft.common.tiles.TileInfusionPillar;
import thaumcraft.common.tiles.TileJarBrain;
import thaumcraft.common.tiles.TileJarFillable;
import thaumcraft.common.tiles.TileJarFillableVoid;
import thaumcraft.common.tiles.TileJarNode;
import thaumcraft.common.tiles.TileLifter;
import thaumcraft.common.tiles.TileMagicBox;
import thaumcraft.common.tiles.TileMagicWorkbenchCharger;
import thaumcraft.common.tiles.TileManaPod;
import thaumcraft.common.tiles.TileMetalDevice;
import thaumcraft.common.tiles.TileMirror;
import thaumcraft.common.tiles.TileMirrorEssentia;
import thaumcraft.common.tiles.TileNitor;
import thaumcraft.common.tiles.TileNode;
import thaumcraft.common.tiles.TileNodeConverter;
import thaumcraft.common.tiles.TileNodeEnergized;
import thaumcraft.common.tiles.TileNodeStabilizer;
import thaumcraft.common.tiles.TileOwned;
import thaumcraft.common.tiles.TilePedestal;
import thaumcraft.common.tiles.TileResearchTable;
import thaumcraft.common.tiles.TileSensor;
import thaumcraft.common.tiles.TileSpa;
import thaumcraft.common.tiles.TileTable;
import thaumcraft.common.tiles.TileThaumatorium;
import thaumcraft.common.tiles.TileThaumatoriumTop;
import thaumcraft.common.tiles.TileTube;
import thaumcraft.common.tiles.TileTubeBuffer;
import thaumcraft.common.tiles.TileTubeFilter;
import thaumcraft.common.tiles.TileTubeOneway;
import thaumcraft.common.tiles.TileTubeRestrict;
import thaumcraft.common.tiles.TileTubeValve;
import thaumcraft.common.tiles.TileVisRelay;
import thaumcraft.common.tiles.TileWandPedestal;
import thaumcraft.common.tiles.TileWarded;
import thaumcraft.common.tiles.TileWardingStone;
import thaumcraft.common.tiles.TileWardingStoneFence;

public class ConfigBlocks {
   public static Fluid FLUXGOO = (new Fluid("fluxGoo", new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluxgoo"), new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluxgoo"))).setGaseous(false).setLuminosity(7).setDensity(8).setViscosity(6000).setColor(0xFFFFFFFF);
   public static Fluid FLUXGAS = (new Fluid("fluxGas", new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluxgas"), new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluxgas"))).setGaseous(true).setLuminosity(7).setDensity(-4).setViscosity(2500).setColor(0xFFFFFFFF);
   public static Fluid FLUIDPURE = (new Fluid("fluidPure", new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluidpure"), new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluidpure"))).setGaseous(false).setLuminosity(10).setViscosity(1000).setColor(0xFFFFFFFF);
   public static Fluid FLUIDDEATH = (new Fluid("fluidDeath", new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluiddeath"), new net.minecraft.util.ResourceLocation("thaumcraft", "blocks/fluiddeath"))).setGaseous(false).setLuminosity(8).setViscosity(1500).setColor(0xFFFFFFFF);
   public static Block blockFluxGoo;
   public static Block blockFluxGas;
   public static Block blockFluidPure;
   public static Block blockFluidDeath;
   public static Block blockHole;
   public static Block blockArcaneFurnace;
   public static Block blockMetalDevice;
   public static Block blockMagicalLog;
   public static Block blockStoneDevice;
   public static Block blockWoodenDevice;
   public static Block blockMagicalLeaves;
   public static Block blockTable;
   public static Block blockChestHungry;
   public static Block blockCustomOre;
   public static Block blockCustomPlant;
   public static Block blockCandle;
   public static Block blockJar;
   public static Block blockArcaneDoor;
   public static Block blockWarded;
   public static Block blockLifter;
   public static Block blockAiry;
   public static Block blockCrystal;
   public static Block blockCosmeticOpaque;
   public static Block blockCosmeticSolid;
   public static Block blockMirror;
   public static Block blockTaint;
   public static Block blockTaintFibres;
   public static Block blockManaPod;
   public static Block blockTube;
   public static Block blockMagicBox;
   public static Block blockEldritch;
   public static Block blockEldritchPortal;
   public static Block blockEssentiaReservoir;
   public static Block blockStairsArcaneStone;
   public static Block blockStairsSilverwood;
   public static Block blockStairsGreatwood;
   public static Block blockStairsEldritch;
   public static Block blockSlabWood;
   public static Block blockSlabStone;
   public static Block blockDoubleSlabWood;
   public static Block blockDoubleSlabStone;
   public static Block blockEldritchNothing;
   public static Block blockAlchemyFurnace;
   public static Block blockLootUrn;
   public static Block blockLootCrate;
   public static int blockCosmeticOpaqueRI;
   public static int blockWoodenDeviceRI;
   public static int blockLifterRI;
   public static int blockCrystalRI;
   public static int blockFluxGasRI;
   public static int blockCustomOreRI;
   public static int blockTaintRI;
   public static int blockTaintFibreRI;
   public static int blockMirrorRI;
   public static int blockCandleRI;
   public static int blockWardedRI;
   public static int blockArcaneFurnaceRI;
   public static int blockMetalDeviceRI;
   public static int blockStoneDeviceRI;
   public static int blockChestHungryRI;
   public static int blockTableRI;
   public static int blockJarRI;
   public static int blockLootUrnRI;
   public static int blockLootCrateRI;
   public static int blockTubeRI;
   public static int blockEssentiaReservoirRI;
   public static int blockEldritchRI;

   public static void registerFluids() {
      FluidRegistry.registerFluid(FLUXGOO);
      FluidRegistry.registerFluid(FLUXGAS);
      FluidRegistry.registerFluid(FLUIDPURE);
      FluidRegistry.registerFluid(FLUIDDEATH);
   }

   public static void init() {
      initializeBlocks();
      registerBlocks();
      registerTileEntities();
      blockCustomOre.setHarvestLevel("pickaxe", 2);
      blockCustomOre.setHarvestLevel("pickaxe", 2);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.BED);
      ThaumcraftApi.portableHoleBlackList.add(blockEldritch);
      ThaumcraftApi.portableHoleBlackList.add(blockEldritchPortal);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.PISTON);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.PISTON_HEAD);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.STICKY_PISTON);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.PISTON_EXTENSION);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.OAK_DOOR);
      ThaumcraftApi.portableHoleBlackList.add(Blocks.IRON_DOOR);
      ThaumcraftApi.portableHoleBlackList.add(blockFluxGoo);
      ThaumcraftApi.portableHoleBlackList.add(blockFluxGas);
      ThaumcraftApi.portableHoleBlackList.add(blockArcaneFurnace);
   }

   private static void initializeBlocks() {
      blockFluxGoo = (new BlockFluxGoo()).setTranslationKey("blockFluxGoo").setRegistryName("thaumcraft", "blockfluxgoo");
      blockFluxGas = (new BlockFluxGas()).setTranslationKey("blockFluxGas").setRegistryName("thaumcraft", "blockfluxgas");
      blockHole = (new BlockHole()).setTranslationKey("blockHole").setRegistryName("thaumcraft", "blockhole");
      blockCustomOre = (new BlockCustomOre()).setTranslationKey("blockCustomOre").setRegistryName("thaumcraft", "blockcustomore");
      blockCustomPlant = (new BlockCustomPlant()).setTranslationKey("blockCustomPlant").setRegistryName("thaumcraft", "blockcustomplant");
      blockMagicalLog = (new BlockMagicalLog()).setTranslationKey("blockMagicalLog").setRegistryName("thaumcraft", "blockmagicallog");
      blockMagicalLeaves = (new BlockMagicalLeaves()).setTranslationKey("blockMagicalLeaves").setRegistryName("thaumcraft", "blockmagicalleaves");
      blockArcaneFurnace = (new BlockArcaneFurnace()).setTranslationKey("blockArcaneFurnace").setRegistryName("thaumcraft", "blockarcanefurnace");
      blockMetalDevice = (new BlockMetalDevice()).setTranslationKey("blockMetalDevice").setRegistryName("thaumcraft", "blockmetaldevice");
      blockAlchemyFurnace = (new BlockAlchemyFurnace()).setTranslationKey("blockAlchemyFurnace").setRegistryName("thaumcraft", "blockalchemyfurnace");
      blockTable = (new BlockTable()).setTranslationKey("blockTable").setRegistryName("thaumcraft", "blocktable");
      blockChestHungry = (new BlockChestHungry()).setTranslationKey("blockChestHungry").setRegistryName("thaumcraft", "blockchesthungry");
      blockCandle = (new BlockCandle()).setTranslationKey("blockCandle").setRegistryName("thaumcraft", "blockcandle");
      blockJar = (new BlockJar()).setTranslationKey("blockJar").setRegistryName("thaumcraft", "blockjar");
      blockArcaneDoor = (new BlockArcaneDoor()).setTranslationKey("blockArcaneDoor").setRegistryName("thaumcraft", "blockarcanedoor");
      blockWoodenDevice = (new BlockWoodenDevice()).setTranslationKey("blockWoodenDevice").setRegistryName("thaumcraft", "blockwoodendevice");
      blockLifter = (new BlockLifter()).setTranslationKey("blockLifter").setRegistryName("thaumcraft", "blocklifter");
      blockAiry = (new BlockAiry()).setTranslationKey("blockAiry").setRegistryName("thaumcraft", "blockairy");
      blockCrystal = (new BlockCrystal()).setTranslationKey("blockCrystal").setRegistryName("thaumcraft", "blockcrystal");
      blockCosmeticOpaque = (new BlockCosmeticOpaque()).setTranslationKey("blockCosmeticOpaque").setRegistryName("thaumcraft", "blockcosmeticopaque");
      blockCosmeticSolid = (new BlockCosmeticSolid()).setTranslationKey("blockCosmeticSolid").setRegistryName("thaumcraft", "blockcosmeticsolid");
      blockMirror = (new BlockMirror()).setTranslationKey("blockMirror").setRegistryName("thaumcraft", "blockmirror");
      blockTaint = (new BlockTaint()).setTranslationKey("blockTaint").setRegistryName("thaumcraft", "blocktaint");
      blockTaintFibres = (new BlockTaintFibres()).setTranslationKey("blockTaintFibres").setRegistryName("thaumcraft", "blocktaintfibres");
      blockStoneDevice = (new BlockStoneDevice()).setTranslationKey("blockStoneDevice").setRegistryName("thaumcraft", "blockstonedevice");
      blockManaPod = (new BlockManaPod()).setTranslationKey("blockManaPod").setRegistryName("thaumcraft", "blockmanapod");
      blockTube = (new BlockTube()).setTranslationKey("blockTube").setRegistryName("thaumcraft", "blocktube");
      blockWarded = (new BlockWarded()).setTranslationKey("blockWarded").setRegistryName("thaumcraft", "blockwarded");
      blockMagicBox = (new BlockMagicBox()).setTranslationKey("blockMagicBox").setRegistryName("thaumcraft", "blockmagicbox");
      blockFluidPure = (new BlockFluidPure()).setTranslationKey("blockFluidPure").setRegistryName("thaumcraft", "blockfluidpure");
      blockFluidDeath = (new BlockFluidDeath()).setTranslationKey("blockFluidDeath").setRegistryName("thaumcraft", "blockfluiddeath");
      blockEldritch = (new BlockEldritch()).setTranslationKey("blockEldritch").setRegistryName("thaumcraft", "blockeldritch");
      blockEldritchPortal = (new BlockEldritchPortal()).setTranslationKey("blockPortalEldritch").setRegistryName("thaumcraft", "blockportaleldritch");
      blockEssentiaReservoir = (new BlockEssentiaReservoir()).setTranslationKey("blockEssentiaReservoir").setRegistryName("thaumcraft", "blockessentiareservoir");
      blockEldritchNothing = (new BlockEldritchNothing()).setTranslationKey("blockPortalNothing").setRegistryName("thaumcraft", "blockportalnothing");
      blockStairsArcaneStone = (new BlockCosmeticStairs(blockCosmeticSolid, 7)).setTranslationKey("blockStairsArcaneStone").setRegistryName("thaumcraft", "blockstairsarcanestone");
      blockStairsGreatwood = (new BlockCosmeticStairs(blockWoodenDevice, 6)).setTranslationKey("blockStairsGreatwood").setRegistryName("thaumcraft", "blockstairsgreatwood");
      blockStairsSilverwood = (new BlockCosmeticStairs(blockWoodenDevice, 7)).setTranslationKey("blockStairsSilverwood").setRegistryName("thaumcraft", "blockstairssilverwood");
      blockStairsEldritch = (new BlockCosmeticStairs(blockCosmeticSolid, 11)).setTranslationKey("blockStairsEldritch").setRegistryName("thaumcraft", "blockstairseldritch");
      blockSlabWood = (new BlockCosmeticWoodSlab(false)).setHardness(2.0F).setResistance(5.0F).setTranslationKey("blockCosmeticSlabWood").setRegistryName("thaumcraft", "blockcosmeticslabwood");
      blockSlabStone = (new BlockCosmeticStoneSlab(false)).setHardness(2.0F).setResistance(10.0F).setTranslationKey("blockCosmeticSlabStone").setRegistryName("thaumcraft", "blockcosmeticslabstone");
      blockDoubleSlabWood = (new BlockCosmeticWoodSlab(true)).setHardness(2.0F).setResistance(5.0F).setTranslationKey("blockCosmeticDoubleSlabWood").setRegistryName("thaumcraft", "blockcosmeticdoubleslabwood");
      blockDoubleSlabStone = (new BlockCosmeticStoneSlab(true)).setHardness(2.0F).setResistance(10.0F).setTranslationKey("blockCosmeticDoubleSlabStone").setRegistryName("thaumcraft", "blockcosmeticdoubleslabstone");
      blockLootUrn = (new BlockLoot(Material.CLAY, "urn", 1)).setTranslationKey("blockLootUrn").setRegistryName("thaumcraft", "blocklooturn");
      blockLootCrate = (new BlockLoot(Material.WOOD, "crate", 2)).setTranslationKey("blockLootCrate").setRegistryName("thaumcraft", "blocklootcrate");
   }

   private static void registerItemBlock(Block b, net.minecraft.item.ItemBlock ib) {
      ForgeRegistries.ITEMS.register(ib.setRegistryName(b.getRegistryName()));
   }

   private static void registerBlocks() {
      ForgeRegistries.BLOCKS.register(blockFluxGoo);
      registerItemBlock(blockFluxGoo, new BlockFluxGooItem(blockFluxGoo));
      ForgeRegistries.BLOCKS.register(blockFluxGas);
      registerItemBlock(blockFluxGas, new BlockFluxGasItem(blockFluxGas));
      ForgeRegistries.BLOCKS.register(blockFluidPure);  // fluid — no ItemBlock
      ForgeRegistries.BLOCKS.register(blockFluidDeath); // fluid — no ItemBlock
      ForgeRegistries.BLOCKS.register(blockCustomOre);
      registerItemBlock(blockCustomOre, new BlockCustomOreItem(blockCustomOre));
      ForgeRegistries.BLOCKS.register(blockMagicalLog);
      registerItemBlock(blockMagicalLog, new BlockMagicalLogItem(blockMagicalLog));
      ForgeRegistries.BLOCKS.register(blockMagicalLeaves);
      registerItemBlock(blockMagicalLeaves, new BlockMagicalLeavesItem(blockMagicalLeaves));
      ForgeRegistries.BLOCKS.register(blockCustomPlant);
      registerItemBlock(blockCustomPlant, new BlockCustomPlantItem(blockCustomPlant));
      ForgeRegistries.BLOCKS.register(blockTaint);
      registerItemBlock(blockTaint, new BlockTaintItem(blockTaint));
      ForgeRegistries.BLOCKS.register(blockTaintFibres);
      registerItemBlock(blockTaintFibres, new BlockTaintFibresItem(blockTaintFibres));
      ForgeRegistries.BLOCKS.register(blockCosmeticOpaque);
      registerItemBlock(blockCosmeticOpaque, new BlockCosmeticOpaqueItem(blockCosmeticOpaque));
      ForgeRegistries.BLOCKS.register(blockCosmeticSolid);
      registerItemBlock(blockCosmeticSolid, new BlockCosmeticSolidItem(blockCosmeticSolid));
      ForgeRegistries.BLOCKS.register(blockCrystal);
      registerItemBlock(blockCrystal, new BlockCrystalItem(blockCrystal));
      ForgeRegistries.BLOCKS.register(blockTube);
      registerItemBlock(blockTube, new BlockTubeItem(blockTube));
      ForgeRegistries.BLOCKS.register(blockMetalDevice);
      registerItemBlock(blockMetalDevice, new BlockMetalDeviceItem(blockMetalDevice));
      ForgeRegistries.BLOCKS.register(blockWoodenDevice);
      registerItemBlock(blockWoodenDevice, new BlockWoodenDeviceItem(blockWoodenDevice));
      ForgeRegistries.BLOCKS.register(blockStoneDevice);
      registerItemBlock(blockStoneDevice, new BlockStoneDeviceItem(blockStoneDevice));
      ForgeRegistries.BLOCKS.register(blockMirror);
      registerItemBlock(blockMirror, new BlockMirrorItem(blockMirror));
      ForgeRegistries.BLOCKS.register(blockTable);
      registerItemBlock(blockTable, new BlockTableItem(blockTable));
      ForgeRegistries.BLOCKS.register(blockChestHungry);
      registerItemBlock(blockChestHungry, new net.minecraft.item.ItemBlock(blockChestHungry));
      ForgeRegistries.BLOCKS.register(blockArcaneDoor);
      registerItemBlock(blockArcaneDoor, new net.minecraft.item.ItemBlock(blockArcaneDoor));
      ForgeRegistries.BLOCKS.register(blockLifter);
      registerItemBlock(blockLifter, new net.minecraft.item.ItemBlock(blockLifter));
      ForgeRegistries.BLOCKS.register(blockMagicBox);
      registerItemBlock(blockMagicBox, new net.minecraft.item.ItemBlock(blockMagicBox));
      ForgeRegistries.BLOCKS.register(blockAlchemyFurnace);
      registerItemBlock(blockAlchemyFurnace, new net.minecraft.item.ItemBlock(blockAlchemyFurnace));
      ForgeRegistries.BLOCKS.register(blockJar);
      registerItemBlock(blockJar, new BlockJarItem(blockJar));
      ForgeRegistries.BLOCKS.register(blockCandle);
      registerItemBlock(blockCandle, new BlockCandleItem(blockCandle));
      ForgeRegistries.BLOCKS.register(blockEldritch);
      registerItemBlock(blockEldritch, new BlockEldritchItem(blockEldritch));
      ForgeRegistries.BLOCKS.register(blockAiry);
      registerItemBlock(blockAiry, new BlockAiryItem(blockAiry));
      ForgeRegistries.BLOCKS.register(blockManaPod);
      registerItemBlock(blockManaPod, new net.minecraft.item.ItemBlock(blockManaPod));
      ForgeRegistries.BLOCKS.register(blockArcaneFurnace);
      registerItemBlock(blockArcaneFurnace, new net.minecraft.item.ItemBlock(blockArcaneFurnace));
      ForgeRegistries.BLOCKS.register(blockWarded);
      registerItemBlock(blockWarded, new net.minecraft.item.ItemBlock(blockWarded));
      ForgeRegistries.BLOCKS.register(blockHole);           // no ItemBlock — placed by focus
      ForgeRegistries.BLOCKS.register(blockEldritchPortal); // no ItemBlock — portal
      ForgeRegistries.BLOCKS.register(blockEssentiaReservoir);
      registerItemBlock(blockEssentiaReservoir, new BlockEssentiaReservoirItem(blockEssentiaReservoir));
      ForgeRegistries.BLOCKS.register(blockEldritchNothing); // no ItemBlock
      ForgeRegistries.BLOCKS.register(blockStairsArcaneStone);
      registerItemBlock(blockStairsArcaneStone, new net.minecraft.item.ItemBlock(blockStairsArcaneStone));
      ForgeRegistries.BLOCKS.register(blockStairsGreatwood);
      registerItemBlock(blockStairsGreatwood, new net.minecraft.item.ItemBlock(blockStairsGreatwood));
      ForgeRegistries.BLOCKS.register(blockStairsSilverwood);
      registerItemBlock(blockStairsSilverwood, new net.minecraft.item.ItemBlock(blockStairsSilverwood));
      ForgeRegistries.BLOCKS.register(blockStairsEldritch);
      registerItemBlock(blockStairsEldritch, new net.minecraft.item.ItemBlock(blockStairsEldritch));
      ForgeRegistries.BLOCKS.register(blockSlabWood);
      registerItemBlock(blockSlabWood, new BlockCosmeticWoodSlabItem(blockSlabWood));
      ForgeRegistries.BLOCKS.register(blockSlabStone);
      registerItemBlock(blockSlabStone, new BlockCosmeticStoneSlabItem(blockSlabStone));
      ForgeRegistries.BLOCKS.register(blockDoubleSlabWood);  // no ItemBlock — internal double slab
      ForgeRegistries.BLOCKS.register(blockDoubleSlabStone); // no ItemBlock — internal double slab
      ForgeRegistries.BLOCKS.register(blockLootUrn);
      registerItemBlock(blockLootUrn, new BlockLootItem(blockLootUrn));
      ForgeRegistries.BLOCKS.register(blockLootCrate);
      registerItemBlock(blockLootCrate, new BlockLootItem(blockLootCrate));
   }

   private static void registerTileEntities() {
      GameRegistry.registerTileEntity(TileHole.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileHole"));
      GameRegistry.registerTileEntity(TileArcaneFurnace.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneFurnace"));
      GameRegistry.registerTileEntity(TileArcaneFurnaceNozzle.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneFurnaceNozzle"));
      GameRegistry.registerTileEntity(TileCrucible.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileCrucible"));
      GameRegistry.registerTileEntity(TileAlembic.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileSiphon"));
      GameRegistry.registerTileEntity(TileJarFillable.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileJar"));
      GameRegistry.registerTileEntity(TileJarFillableVoid.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileJarVoid"));
      GameRegistry.registerTileEntity(TileJarNode.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileJarNode"));
      GameRegistry.registerTileEntity(TileJarBrain.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileJarBrain"));
      GameRegistry.registerTileEntity(TileResearchTable.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileResearchTable"));
      GameRegistry.registerTileEntity(TileTable.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTable"));
      GameRegistry.registerTileEntity(TileArcaneWorkbench.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneWorkbench"));
      GameRegistry.registerTileEntity(TileChestHungry.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileChestHungry"));
      GameRegistry.registerTileEntity(TileBellows.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileBellows"));
      GameRegistry.registerTileEntity(TileSensor.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileSensor"));
      GameRegistry.registerTileEntity(TileArcanePressurePlate.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcanePressurePlate"));
      GameRegistry.registerTileEntity(TileArcaneBore.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneBore"));
      GameRegistry.registerTileEntity(TileArcaneBoreBase.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneBoreBase"));
      GameRegistry.registerTileEntity(TileArcaneLamp.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneLamp"));
      GameRegistry.registerTileEntity(TileArcaneLampLight.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneLampLight"));
      GameRegistry.registerTileEntity(TileArcaneLampGrowth.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneLampGrowth"));
      GameRegistry.registerTileEntity(TileArcaneLampFertility.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileArcaneLampFertility"));
      GameRegistry.registerTileEntity(TileOwned.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileOwned"));
      GameRegistry.registerTileEntity(TileLifter.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileLifter"));
      GameRegistry.registerTileEntity(TileNitor.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileNitor"));
      GameRegistry.registerTileEntity(TileNode.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileNode"));
      GameRegistry.registerTileEntity(TileCrystal.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileCrystal"));
      GameRegistry.registerTileEntity(TileEldritchCrystal.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchCrystal"));
      GameRegistry.registerTileEntity(TileMirror.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileMirror"));
      GameRegistry.registerTileEntity(TileMirrorEssentia.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileMirrorEssentia"));
      GameRegistry.registerTileEntity(TilePedestal.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TilePedestal"));
      GameRegistry.registerTileEntity(TileWandPedestal.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileWandPedestal"));
      GameRegistry.registerTileEntity(TileInfusionMatrix.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileInfusionStone"));
      GameRegistry.registerTileEntity(TileInfusionPillar.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileInfusionPillar"));
      GameRegistry.registerTileEntity(TileAlchemyFurnace.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileAlchemyFurnace"));
      GameRegistry.registerTileEntity(TileAlchemyFurnaceAdvanced.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileAlchemyFurnaceAdvanced"));
      GameRegistry.registerTileEntity(TileAlchemyFurnaceAdvancedNozzle.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileAlchemyFurnaceAdvancedNozzle"));
      GameRegistry.registerTileEntity(TileDeconstructionTable.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileDeconstructionTable"));
      GameRegistry.registerTileEntity(TileEtherealBloom.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TilePurifyTotem"));
      GameRegistry.registerTileEntity(TileTube.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTube"));
      GameRegistry.registerTileEntity(TileTubeValve.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTubeValve"));
      GameRegistry.registerTileEntity(TileCentrifuge.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileCentrifuge"));
      GameRegistry.registerTileEntity(TileTubeFilter.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTubeFilter"));
      GameRegistry.registerTileEntity(TileTubeBuffer.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTubeBuffer"));
      GameRegistry.registerTileEntity(TileTubeRestrict.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTubeRestrict"));
      GameRegistry.registerTileEntity(TileTubeOneway.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileTubeOneway"));
      GameRegistry.registerTileEntity(TileThaumatorium.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileThaumatorium"));
      GameRegistry.registerTileEntity(TileThaumatoriumTop.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileThaumatoriumTop"));
      GameRegistry.registerTileEntity(TileMetalDevice.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileMetalDevice"));
      GameRegistry.registerTileEntity(TileBrainbox.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileBrainbox"));
      GameRegistry.registerTileEntity(TileWarded.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileWarded"));
      GameRegistry.registerTileEntity(TileGrate.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileGrate"));
      GameRegistry.registerTileEntity(TileWardingStone.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileWardingStone"));
      GameRegistry.registerTileEntity(TileWardingStoneFence.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileWardingStoneFence"));
      GameRegistry.registerTileEntity(TileMagicBox.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileMagicBox"));
      GameRegistry.registerTileEntity(TileNodeStabilizer.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileNodeStabilizer"));
      GameRegistry.registerTileEntity(TileVisRelay.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileVisRelay"));
      GameRegistry.registerTileEntity(TileNodeEnergized.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileNodeEnergized"));
      GameRegistry.registerTileEntity(TileNodeConverter.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileNodeConverter"));
      GameRegistry.registerTileEntity(TileMagicWorkbenchCharger.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileMagicWorkbenchCharger"));
      GameRegistry.registerTileEntity(TileManaPod.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileManaPod"));
      GameRegistry.registerTileEntity(TileSpa.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileSpa"));
      GameRegistry.registerTileEntity(TileEldritchAltar.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchAltar"));
      GameRegistry.registerTileEntity(TileEldritchObelisk.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchObelisk"));
      GameRegistry.registerTileEntity(TileEldritchCap.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchCap"));
      GameRegistry.registerTileEntity(TileEldritchStone.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchStone"));
      GameRegistry.registerTileEntity(TileBanner.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileBanner"));
      GameRegistry.registerTileEntity(thaumcraft.common.tiles.TilePlank.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TilePlank"));
      GameRegistry.registerTileEntity(TileEldritchPortal.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchPortal"));
      GameRegistry.registerTileEntity(TileEssentiaReservoir.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEssentiaReservoir"));
      GameRegistry.registerTileEntity(TileEssentiaCrystalizer.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEssentiaCrystalizer"));
      GameRegistry.registerTileEntity(TileEldritchNothing.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchNothing"));
      GameRegistry.registerTileEntity(TileEldritchLock.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchLock"));
      GameRegistry.registerTileEntity(TileEldritchCrabSpawner.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchCrabSpawner"));
      GameRegistry.registerTileEntity(TileFocalManipulator.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileFocalManipulator"));
      GameRegistry.registerTileEntity(TileFluxScrubber.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileFluxScrubber"));
      GameRegistry.registerTileEntity(TileEldritchTrap.class, new net.minecraft.util.ResourceLocation("thaumcraft", "TileEldritchTrap"));
   }

   static {
      // FLUIDPURE and FLUIDDEATH are now field initializers
      blockCosmeticOpaqueRI = -1;
      blockWoodenDeviceRI = -1;
      blockLifterRI = -1;
      blockCrystalRI = -1;
      blockFluxGasRI = -1;
      blockCustomOreRI = -1;
      blockTaintRI = -1;
      blockTaintFibreRI = -1;
      blockMirrorRI = -1;
      blockCandleRI = -1;
      blockWardedRI = -1;
      blockArcaneFurnaceRI = -1;
      blockMetalDeviceRI = -1;
      blockStoneDeviceRI = -1;
      blockChestHungryRI = -1;
      blockTableRI = -1;
      blockJarRI = -1;
      blockLootUrnRI = -1;
      blockLootCrateRI = -1;
      blockTubeRI = -1;
      blockEssentiaReservoirRI = -1;
      blockEldritchRI = -1;
   }
}
