package thaumcraft.common.config;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.PotionEffect;
import net.minecraft.potion.PotionHelper;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;

public class ConfigAspects {
   private static final int[] ALLMETA = new int[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
   public static String[] dyes = new String[]{"dyeBlack", "dyeRed", "dyeGreen", "dyeBrown", "dyeBlue", "dyePurple", "dyeCyan", "dyeLightGray", "dyeGray", "dyePink", "dyeLime", "dyeYellow", "dyeLightBlue", "dyeMagenta", "dyeOrange", "dyeWhite"};

   public static void init() {
      registerItemAspects();
      registerEntityAspects();
   }

   private static void registerEntityAspects() {
      ThaumcraftApi.registerEntityTag("Zombie", (new AspectList()).add(Aspect.UNDEAD, 2).add(Aspect.MAN, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerEntityTag("Giant", (new AspectList()).add(Aspect.UNDEAD, 4).add(Aspect.MAN, 3).add(Aspect.EARTH, 3));
      ThaumcraftApi.registerEntityTag("Skeleton", (new AspectList()).add(Aspect.UNDEAD, 3).add(Aspect.MAN, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerEntityTag("Skeleton", (new AspectList()).add(Aspect.UNDEAD, 4).add(Aspect.MAN, 1).add(Aspect.FIRE, 2), new ThaumcraftApi.EntityTagsNBT("SkeletonType", (byte)1));
      ThaumcraftApi.registerEntityTag("Creeper", (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("Creeper", (new AspectList()).add(Aspect.PLANT, 3).add(Aspect.FIRE, 3).add(Aspect.ENERGY, 3), new ThaumcraftApi.EntityTagsNBT("powered", (byte)1));
      ThaumcraftApi.registerEntityTag("EntityHorse", (new AspectList()).add(Aspect.BEAST, 4).add(Aspect.EARTH, 1).add(Aspect.AIR, 1));
      ThaumcraftApi.registerEntityTag("Pig", (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerEntityTag("XPOrb", (new AspectList()).add(Aspect.MIND, 5));
      ThaumcraftApi.registerEntityTag("Sheep", (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerEntityTag("Cow", (new AspectList()).add(Aspect.BEAST, 3).add(Aspect.EARTH, 3));
      ThaumcraftApi.registerEntityTag("MushroomCow", (new AspectList()).add(Aspect.BEAST, 3).add(Aspect.PLANT, 1).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerEntityTag("SnowMan", (new AspectList()).add(Aspect.COLD, 3).add(Aspect.WATER, 1));
      ThaumcraftApi.registerEntityTag("Ozelot", (new AspectList()).add(Aspect.BEAST, 3).add(Aspect.ENTROPY, 3));
      ThaumcraftApi.registerEntityTag("Chicken", (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.FLIGHT, 2).add(Aspect.AIR, 1));
      ThaumcraftApi.registerEntityTag("Squid", (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.WATER, 2));
      ThaumcraftApi.registerEntityTag("Wolf", (new AspectList()).add(Aspect.BEAST, 3).add(Aspect.EARTH, 3));
      ThaumcraftApi.registerEntityTag("Bat", (new AspectList()).add(Aspect.BEAST, 1).add(Aspect.FLIGHT, 1).add(Aspect.AIR, 1));
      ThaumcraftApi.registerEntityTag("Boat", (new AspectList()).add(Aspect.MECHANISM, 2).add(Aspect.WATER, 2));
      ThaumcraftApi.registerEntityTag("Spider", (new AspectList()).add(Aspect.BEAST, 3).add(Aspect.ENTROPY, 2));
      ThaumcraftApi.registerEntityTag("Slime", (new AspectList()).add(Aspect.SLIME, 2).add(Aspect.WATER, 2));
      ThaumcraftApi.registerEntityTag("Ghast", (new AspectList()).add(Aspect.UNDEAD, 3).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("PigZombie", (new AspectList()).add(Aspect.UNDEAD, 4).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("Enderman", (new AspectList()).add(Aspect.ELDRITCH, 4).add(Aspect.TRAVEL, 2).add(Aspect.AIR, 2));
      ThaumcraftApi.registerEntityTag("CaveSpider", (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.POISON, 2).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerEntityTag("Silverfish", (new AspectList()).add(Aspect.BEAST, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerEntityTag("Blaze", (new AspectList()).add(Aspect.ELDRITCH, 4).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerEntityTag("LavaSlime", (new AspectList()).add(Aspect.SLIME, 3).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("EnderDragon", (new AspectList()).add(Aspect.ELDRITCH, 20).add(Aspect.BEAST, 20).add(Aspect.ENTROPY, 20));
      ThaumcraftApi.registerEntityTag("WitherBoss", (new AspectList()).add(Aspect.UNDEAD, 20).add(Aspect.ENTROPY, 20).add(Aspect.FIRE, 15));
      ThaumcraftApi.registerEntityTag("Witch", (new AspectList()).add(Aspect.MAN, 3).add(Aspect.MAGIC, 2).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerEntityTag("Villager", (new AspectList()).add(Aspect.MAN, 3).add(Aspect.AIR, 2));
      ThaumcraftApi.registerEntityTag("VillagerGolem", (new AspectList()).add(Aspect.METAL, 4).add(Aspect.EARTH, 3));
      ThaumcraftApi.registerEntityTag("MinecartRideable", (new AspectList()).add(Aspect.MECHANISM, 3).add(Aspect.AIR, 2));
      ThaumcraftApi.registerEntityTag("MinecartChest", (new AspectList()).add(Aspect.MECHANISM, 3).add(Aspect.AIR, 1).add(Aspect.VOID, 1));
      ThaumcraftApi.registerEntityTag("MinecartFurnace", (new AspectList()).add(Aspect.MECHANISM, 3).add(Aspect.AIR, 1).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerEntityTag("MinecartTNT", (new AspectList()).add(Aspect.MECHANISM, 3).add(Aspect.AIR, 1).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerEntityTag("MinecartHopper", (new AspectList()).add(Aspect.MECHANISM, 3).add(Aspect.AIR, 1).add(Aspect.EXCHANGE, 1));
      ThaumcraftApi.registerEntityTag("MinecartSpawner", (new AspectList()).add(Aspect.MECHANISM, 3).add(Aspect.AIR, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerEntityTag("EnderCrystal", (new AspectList()).add(Aspect.ELDRITCH, 3).add(Aspect.MAGIC, 3).add(Aspect.HEAL, 3));
      ThaumcraftApi.registerEntityTag("ItemFrame", (new AspectList()).add(Aspect.SENSES, 3).add(Aspect.CLOTH, 1));
      ThaumcraftApi.registerEntityTag("Painting", (new AspectList()).add(Aspect.SENSES, 5).add(Aspect.CLOTH, 3));
      ThaumcraftApi.registerEntityTag("Thaumcraft.PrimalOrb", (new AspectList()).add(Aspect.AIR, 5).add(Aspect.ENTROPY, 10).add(Aspect.MAGIC, 10).add(Aspect.ENERGY, 10));
      ThaumcraftApi.registerEntityTag("Thaumcraft.Firebat", (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.FLIGHT, 1).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", (new AspectList()).add(Aspect.MAN, 2).add(Aspect.MAGIC, 2).add(Aspect.EXCHANGE, 2).add(Aspect.GREED, 2), new ThaumcraftApi.EntityTagsNBT("PechType", (byte)0));
      ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", (new AspectList()).add(Aspect.MAN, 2).add(Aspect.MAGIC, 2).add(Aspect.EXCHANGE, 2).add(Aspect.WEAPON, 2), new ThaumcraftApi.EntityTagsNBT("PechType", (byte)1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", (new AspectList()).add(Aspect.MAN, 2).add(Aspect.MAGIC, 4).add(Aspect.EXCHANGE, 2), new ThaumcraftApi.EntityTagsNBT("PechType", (byte)2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.ThaumSlime", (new AspectList()).add(Aspect.SLIME, 2).add(Aspect.MAGIC, 1).add(Aspect.WATER, 1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.BrainyZombie", (new AspectList()).add(Aspect.UNDEAD, 3).add(Aspect.MAN, 1).add(Aspect.MIND, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.GiantBrainyZombie", (new AspectList()).add(Aspect.UNDEAD, 4).add(Aspect.MAN, 2).add(Aspect.MIND, 1).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.Taintacle", (new AspectList()).add(Aspect.TAINT, 3).add(Aspect.WATER, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintacleTiny", (new AspectList()).add(Aspect.TAINT, 1).add(Aspect.WATER, 1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSpider", (new AspectList()).add(Aspect.TAINT, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSpore", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.AIR, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSwarmer", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.AIR, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSwarm", (new AspectList()).add(Aspect.TAINT, 3).add(Aspect.AIR, 3));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintedPig", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintedSheep", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintedCow", (new AspectList()).add(Aspect.TAINT, 3).add(Aspect.EARTH, 3));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintedChicken", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.FLIGHT, 2).add(Aspect.AIR, 1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintedVillager", (new AspectList()).add(Aspect.TAINT, 3).add(Aspect.AIR, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.TaintedCreeper", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.MindSpider", (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchGuardian", (new AspectList()).add(Aspect.ELDRITCH, 4).add(Aspect.DEATH, 2).add(Aspect.UNDEAD, 4));
      ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchOrb", (new AspectList()).add(Aspect.ELDRITCH, 2).add(Aspect.DEATH, 2));
      ThaumcraftApi.registerEntityTag("Thaumcraft.CultistKnight", (new AspectList()).add(Aspect.ELDRITCH, 1).add(Aspect.MAN, 2).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerEntityTag("Thaumcraft.CultistCleric", (new AspectList()).add(Aspect.ELDRITCH, 1).add(Aspect.MAN, 2).add(Aspect.ENTROPY, 1));

      for(Aspect tag : Aspect.aspects.values()) {
         ThaumcraftApi.registerEntityTag("Thaumcraft.Wisp", (new AspectList()).add(tag, 2).add(Aspect.MAGIC, 1).add(Aspect.AIR, 1), new ThaumcraftApi.EntityTagsNBT("Type", tag.getTag()));
      }

      ThaumcraftApi.registerEntityTag("Thaumcraft.Golem", (new AspectList()).add(Aspect.AIR, 2).add(Aspect.EARTH, 2).add(Aspect.MAGIC, 2));
   }

   private static void registerItemAspects() {
      ThaumcraftApi.registerObjectTag("stone", (new AspectList()).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerObjectTag("cobblestone", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerObjectTag("logWood", (new AspectList()).add(Aspect.TREE, 4));
      ThaumcraftApi.registerObjectTag("plankWood", (new AspectList()).add(Aspect.TREE, 1));
      ThaumcraftApi.registerObjectTag("slabWood", (new AspectList()).add(Aspect.TREE, 1));
      ThaumcraftApi.registerObjectTag("stairWood", (new AspectList()).add(Aspect.TREE, 1));
      ThaumcraftApi.registerObjectTag("stickWood", (new AspectList()).add(Aspect.TREE, 1));
      ThaumcraftApi.registerObjectTag("treeSapling", (new AspectList()).add(Aspect.TREE, 1).add(Aspect.PLANT, 2));
      ThaumcraftApi.registerObjectTag("treeLeaves", (new AspectList()).add(Aspect.PLANT, 1));

      for(int i = 0; i < 16; ++i) {
         ThaumcraftApi.registerObjectTag(dyes[i], (new AspectList()).add(Aspect.SENSES, 1));
      }

      ThaumcraftApi.registerObjectTag("oreLapis", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.SENSES, 3));
      ThaumcraftApi.registerObjectTag("oreDiamond", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.GREED, 3).add(Aspect.CRYSTAL, 3));
      ThaumcraftApi.registerObjectTag("gemDiamond", (new AspectList()).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag("oreRedstone", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ENERGY, 2).add(Aspect.MECHANISM, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LIT_REDSTONE_ORE), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ENERGY, 3).add(Aspect.MECHANISM, 2));
      ThaumcraftApi.registerObjectTag("oreEmerald", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.GREED, 4).add(Aspect.CRYSTAL, 3));
      ThaumcraftApi.registerObjectTag("gemEmerald", (new AspectList()).add(Aspect.CRYSTAL, 4).add(Aspect.GREED, 5));
      ThaumcraftApi.registerObjectTag("oreQuartz", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.CRYSTAL, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.QUARTZ), (new AspectList()).add(Aspect.CRYSTAL, 1).add(Aspect.ENERGY, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.GOLD_NUGGET), (new AspectList()).add(Aspect.METAL, 1));
      ThaumcraftApi.registerObjectTag("nuggetIron", (new AspectList()).add(Aspect.METAL, 1));
      ThaumcraftApi.registerObjectTag("oreIron", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.METAL, 3));
      ThaumcraftApi.registerObjectTag("dustIron", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.IRON_INGOT), (new AspectList()).add(Aspect.METAL, 4));
      ThaumcraftApi.registerObjectTag("oreGold", (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.METAL, 2).add(Aspect.GREED, 1));
      ThaumcraftApi.registerObjectTag("dustGold", (new AspectList()).add(Aspect.METAL, 2).add(Aspect.ENTROPY, 1).add(Aspect.GREED, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.GOLD_INGOT), (new AspectList()).add(Aspect.METAL, 3).add(Aspect.GREED, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.COAL_ORE), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ENERGY, 2).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.COAL, 1, 32767), (new AspectList()).add(Aspect.ENERGY, 2).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerObjectTag("dustRedstone", (new AspectList()).add(Aspect.ENERGY, 2).add(Aspect.MECHANISM, 1));
      ThaumcraftApi.registerObjectTag("dustGlowstone", (new AspectList()).add(Aspect.SENSES, 1).add(Aspect.LIGHT, 2));
      ThaumcraftApi.registerObjectTag("glowstone", (new AspectList()).add(Aspect.SENSES, 3).add(Aspect.LIGHT, 10));
      if (Config.foundCopperIngot) {
         ThaumcraftApi.registerObjectTag("nuggetCopper", (new AspectList()).add(Aspect.METAL, 1));
         ThaumcraftApi.registerObjectTag("ingotCopper", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.EXCHANGE, 1));
         ThaumcraftApi.registerObjectTag("dustCopper", (new AspectList()).add(Aspect.METAL, 2).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 1));
         ThaumcraftApi.registerObjectTag("oreCopper", (new AspectList()).add(Aspect.METAL, 2).add(Aspect.EARTH, 1).add(Aspect.EXCHANGE, 1));
         ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 17), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 5).add(Aspect.EARTH, 1).add(Aspect.EXCHANGE, 2));
      }

      if (Config.foundTinIngot) {
         ThaumcraftApi.registerObjectTag("nuggetTin", (new AspectList()).add(Aspect.METAL, 1));
         ThaumcraftApi.registerObjectTag("ingotTin", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.CRYSTAL, 1));
         ThaumcraftApi.registerObjectTag("dustTin", (new AspectList()).add(Aspect.METAL, 2).add(Aspect.ENTROPY, 1).add(Aspect.CRYSTAL, 1));
         ThaumcraftApi.registerObjectTag("oreTin", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.ENTROPY, 1).add(Aspect.CRYSTAL, 1));
         ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 18), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 5).add(Aspect.EARTH, 1).add(Aspect.CRYSTAL, 2));
      }

      if (Config.foundSilverIngot) {
         ThaumcraftApi.registerObjectTag("nuggetSilver", (new AspectList()).add(Aspect.METAL, 1));
         ThaumcraftApi.registerObjectTag("ingotSilver", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.GREED, 1));
         ThaumcraftApi.registerObjectTag("dustSilver", (new AspectList()).add(Aspect.METAL, 2).add(Aspect.ENTROPY, 1).add(Aspect.GREED, 1));
         ThaumcraftApi.registerObjectTag("oreSilver", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.ENTROPY, 1).add(Aspect.GREED, 1));
         ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 19), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 5).add(Aspect.EARTH, 1).add(Aspect.GREED, 2));
      }

      if (Config.foundLeadIngot) {
         ThaumcraftApi.registerObjectTag("nuggetLead", (new AspectList()).add(Aspect.METAL, 1));
         ThaumcraftApi.registerObjectTag("ingotLead", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.ORDER, 1));
         ThaumcraftApi.registerObjectTag("dustLead", (new AspectList()).add(Aspect.METAL, 2).add(Aspect.ENTROPY, 1).add(Aspect.ORDER, 1));
         ThaumcraftApi.registerObjectTag("oreLead", (new AspectList()).add(Aspect.METAL, 3).add(Aspect.ENTROPY, 1).add(Aspect.ORDER, 1));
         ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 20), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 5).add(Aspect.EARTH, 1).add(Aspect.ORDER, 2));
      }

      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BEDROCK), (new AspectList()).add(Aspect.VOID, 16).add(Aspect.ENTROPY, 16).add(Aspect.EARTH, 16).add(Aspect.DARKNESS, 16));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DIRT, 1, 32767), (new AspectList()).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DIRT, 1, 2), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.FARMLAND, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.HARVEST, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SAND, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GRASS), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CLAY_BALL, 1, 32767), (new AspectList()).add(Aspect.WATER, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.END_STONE), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.DARKNESS, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GRAVEL), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MYCELIUM), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CLAY, 1, 32767), (new AspectList()).add(Aspect.EARTH, 3).add(Aspect.WATER, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.HARDENED_CLAY, 1, 32767), (new AspectList()).add(Aspect.EARTH, 4).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STAINED_HARDENED_CLAY, 1, 32767), (new AspectList()).add(Aspect.EARTH, 3).add(Aspect.FIRE, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.BRICK, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.NETHERBRICK, 1, 32767), (new AspectList()).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SOUL_SAND, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.TRAP, 1).add(Aspect.SOUL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.NETHERRACK, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.EARTH, 1).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.NETHER_BRICK), (new AspectList()).add(Aspect.EARTH, 2).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GLASS, 1, 32767), (new AspectList()).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STAINED_GLASS, 1, 32767), (new AspectList()).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MOSSY_COBBLESTONE, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.PLANT, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.OBSIDIAN, 1, 32767), (new AspectList()).add(Aspect.EARTH, 2).add(Aspect.FIRE, 2).add(Aspect.DARKNESS, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MONSTER_EGG, 1, 32767), (new AspectList()).add(Aspect.EARTH, 2).add(Aspect.BEAST, 1).add(Aspect.TRAP, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 32767), (new AspectList()).add(Aspect.EARTH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 1), (new AspectList(new ItemStack(Blocks.STONEBRICK))).remove(Aspect.EARTH, 1).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 2), (new AspectList(new ItemStack(Blocks.STONEBRICK))).remove(Aspect.EARTH, 1).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 3), (new AspectList(new ItemStack(Blocks.STONEBRICK))).remove(Aspect.EARTH, 1).add(Aspect.ORDER, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.SANDSTONE, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).remove(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SANDSTONE, 1, 1), (new AspectList(new ItemStack(Blocks.SANDSTONE))).remove(Aspect.EARTH, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SANDSTONE, 1, 2), (new AspectList(new ItemStack(Blocks.SANDSTONE))).remove(Aspect.EARTH, 1).add(Aspect.ORDER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.TALLGRASS, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.AIR, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.AIR, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WATERLILY, 1, 32767), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.WATER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DEADBUSH, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.VINE, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.WHEAT_SEEDS, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.MELON_SEEDS, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.PUMPKIN_SEEDS, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.MELON, 1, 32767), (new AspectList()).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.NETHER_WART), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_FLOWER, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.LIFE, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.YELLOW_FLOWER, 1, 32767), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.LIFE, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CACTUS), (new AspectList()).add(Aspect.PLANT, 3).add(Aspect.WATER, 1).add(Aspect.ENTROPY, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BROWN_MUSHROOM), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.DARKNESS, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_MUSHROOM), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.DARKNESS, 1).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BROWN_MUSHROOM_BLOCK, 1, 32767), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.DARKNESS, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_MUSHROOM_BLOCK, 1, 32767), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.DARKNESS, 1).add(Aspect.FIRE, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.REEDS), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.WATER, 1).add(Aspect.AIR, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.WHEAT), (new AspectList()).add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.APPLE), (new AspectList()).add(Aspect.CROP, 2).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CARROT), (new AspectList()).add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.POTATO), (new AspectList()).add(Aspect.CROP, 1).add(Aspect.HUNGER, 1).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.BAKED_POTATO), (new AspectList()).add(Aspect.CROP, 1).add(Aspect.HUNGER, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.POISONOUS_POTATO), (new AspectList()).add(Aspect.CROP, 1).add(Aspect.POISON, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PUMPKIN, 1, 32767), (new AspectList()).add(Aspect.CROP, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.MELON_BLOCK, 1, 32767), (new AspectList()).add(Aspect.CROP, 2).remove(Aspect.HUNGER, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.NAME_TAG, 1, 32767), (new AspectList()).add(Aspect.MIND, 2).add(Aspect.BEAST, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.IRON_HORSE_ARMOR, 1, 32767), (new AspectList()).add(Aspect.ARMOR, 2).add(Aspect.BEAST, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.GOLDEN_HORSE_ARMOR, 1, 32767), (new AspectList()).add(Aspect.ARMOR, 4).add(Aspect.BEAST, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.DIAMOND_HORSE_ARMOR, 1, 32767), (new AspectList()).add(Aspect.ARMOR, 6).add(Aspect.BEAST, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.FIRE, 1, 32767), (new AspectList()).add(Aspect.FIRE, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WATER, 1, 32767), (new AspectList()).add(Aspect.WATER, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LAVA, 1, 32767), (new AspectList()).add(Aspect.FIRE, 3).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.ICE, 1, 32767), (new AspectList()).add(Aspect.COLD, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PACKED_ICE, 1, 32767), (new AspectList()).add(Aspect.COLD, 3).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SNOWBALL, 1, 32767), (new AspectList()).add(Aspect.COLD, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKIE, 1, 32767), (new AspectList()).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.POTIONITEM), (new AspectList()).add(Aspect.WATER, 1).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.TORCH, 1, 32767), (new AspectList()).add(Aspect.LIGHT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WEB, 1, 32767), (new AspectList()).add(Aspect.TRAP, 2).add(Aspect.CLOTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.FLINT, 1, 32767), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.TOOL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.STRING, 1, 32767), (new AspectList()).add(Aspect.BEAST, 1).add(Aspect.CLOTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SLIME_BALL), (new AspectList()).add(Aspect.SLIME, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.LEATHER, 1, 32767), (new AspectList()).add(Aspect.CLOTH, 2).add(Aspect.BEAST, 1).add(Aspect.ARMOR, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.ROTTEN_FLESH, 1, 32767), (new AspectList()).add(Aspect.MAN, 1).add(Aspect.FLESH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.FEATHER, 1, 32767), (new AspectList()).add(Aspect.FLIGHT, 2).add(Aspect.AIR, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.BONE, 1, 32767), (new AspectList()).add(Aspect.DEATH, 2).add(Aspect.FLESH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.EGG, 1, 32767), (new AspectList()).add(Aspect.SLIME, 1).add(Aspect.LIFE, 1).add(Aspect.BEAST, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SPIDER_EYE, 1, 32767), (new AspectList()).add(Aspect.SENSES, 2).add(Aspect.BEAST, 2).add(Aspect.POISON, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.GUNPOWDER, 1, 32767), (new AspectList()).add(Aspect.FIRE, 4).add(Aspect.ENTROPY, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WOOL, 1, 32767), (new AspectList()).add(Aspect.CLOTH, 4).add(Aspect.CRAFT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.FISH, 1, 32767), (new AspectList()).add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.WATER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_FISH, 1, 32767), (new AspectList()).add(Aspect.CRAFT, 1).add(Aspect.FLESH, 4).add(Aspect.HUNGER, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHICKEN, 1, 32767), (new AspectList()).add(Aspect.FLESH, 3).add(Aspect.LIFE, 2).add(Aspect.BEAST, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_CHICKEN, 1, 32767), (new AspectList()).add(Aspect.CRAFT, 1).add(Aspect.FLESH, 4).add(Aspect.HUNGER, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.PORKCHOP, 1, 32767), (new AspectList()).add(Aspect.FLESH, 3).add(Aspect.LIFE, 1).add(Aspect.BEAST, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_PORKCHOP, 1, 32767), (new AspectList()).add(Aspect.CRAFT, 1).add(Aspect.FLESH, 3).add(Aspect.HUNGER, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.BEEF, 1, 32767), (new AspectList()).add(Aspect.FLESH, 4).add(Aspect.LIFE, 2).add(Aspect.BEAST, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_BEEF, 1, 32767), (new AspectList()).add(Aspect.CRAFT, 1).add(Aspect.FLESH, 4).add(Aspect.HUNGER, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.BLAZE_ROD, 1, 32767), (new AspectList()).add(Aspect.FIRE, 4).add(Aspect.MAGIC, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SADDLE, 1, 32767), (new AspectList()).add(Aspect.BEAST, 2).add(Aspect.CLOTH, 3).add(Aspect.TRAVEL, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.ENDER_PEARL, 1, 32767), (new AspectList()).add(Aspect.ELDRITCH, 4).add(Aspect.MAGIC, 2).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.GHAST_TEAR, 1, 32767), (new AspectList()).add(Aspect.WATER, 1).add(Aspect.UNDEAD, 4).add(Aspect.SOUL, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 0), (new AspectList()).add(Aspect.DEATH, 4).add(Aspect.SOUL, 4).add(Aspect.UNDEAD, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 1), (new AspectList()).add(Aspect.DEATH, 4).add(Aspect.SOUL, 4).add(Aspect.UNDEAD, 4).add(Aspect.POISON, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 2), (new AspectList()).add(Aspect.DEATH, 4).add(Aspect.SOUL, 4).add(Aspect.FLESH, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 3), (new AspectList()).add(Aspect.DEATH, 4).add(Aspect.SOUL, 4).add(Aspect.MAN, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 4), (new AspectList()).add(Aspect.DEATH, 4).add(Aspect.SOUL, 4).add(Aspect.ENTROPY, 2).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_11), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_13), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.WATER, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_CAT), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.BEAST, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_CHIRP), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.EARTH, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_FAR), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.ELDRITCH, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_MALL), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.MAN, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_MELLOHI), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.CRAFT, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_STAL), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.DARKNESS, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_STRAD), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.MECHANISM, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_WARD), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.MAGIC, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_BLOCKS), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.TOOL, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_WAIT), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.AIR, 4).add(Aspect.TRAP, 4).add(Aspect.GREED, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.NETHER_STAR), (new AspectList()).add(Aspect.ELDRITCH, 8).add(Aspect.MAGIC, 8).add(Aspect.ORDER, 8).add(Aspect.LIGHT, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_HELMET, 1, 32767), (new AspectList()).add(Aspect.METAL, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_CHESTPLATE, 1, 32767), (new AspectList()).add(Aspect.METAL, 12));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_LEGGINGS, 1, 32767), (new AspectList()).add(Aspect.METAL, 11));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_BOOTS, 1, 32767), (new AspectList()).add(Aspect.METAL, 7));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.PAPER), (new AspectList()).add(Aspect.MIND, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BOOK), (new AspectList()).add(Aspect.MIND, 3));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ENCHANTED_BOOK), new AspectList(new ItemStack(Items.BOOK)));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.BOOKSHELF), (new AspectList()).add(Aspect.MIND, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DRAGON_EGG), (new AspectList()).add(Aspect.ELDRITCH, 8).add(Aspect.BEAST, 8).add(Aspect.MAGIC, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PORTAL, 1, 32767), (new AspectList()).add(Aspect.FIRE, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.END_PORTAL, 1, 32767), (new AspectList()).add(Aspect.ELDRITCH, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.END_PORTAL_FRAME, 1, 32767), (new AspectList()).add(Aspect.ELDRITCH, 4).add(Aspect.MECHANISM, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MOB_SPAWNER, 1, 32767), (new AspectList()).add(Aspect.BEAST, 4).add(Aspect.TRAVEL, 4).add(Aspect.UNDEAD, 4).add(Aspect.MAGIC, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ENDER_EYE), (new AspectList()).add(Aspect.SENSES, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ARROW), (new AspectList()).add(Aspect.WEAPON, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GLASS_BOTTLE), (new AspectList()).add(Aspect.VOID, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.CHEST, 1, 32767), (new AspectList()).add(Aspect.VOID, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GOLDEN_APPLE, 1, 0), (new AspectList()).add(Aspect.MAGIC, 2).add(Aspect.HEAL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GOLDEN_APPLE, 1, 1), (new AspectList()).add(Aspect.MAGIC, 4).add(Aspect.HEAL, 8));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BOWL), (new AspectList()).add(Aspect.VOID, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.MUSHROOM_STEW), (new AspectList()).add(Aspect.HUNGER, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.MINECART), (new AspectList()).add(Aspect.MECHANISM, 2).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.IRON_DOOR), (new AspectList()).add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.OAK_DOOR), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SPRUCE_DOOR), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ACACIA_DOOR), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BIRCH_DOOR), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.JUNGLE_DOOR), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.DARK_OAK_DOOR), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BOAT), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SPRUCE_BOAT), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ACACIA_BOAT), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BIRCH_BOAT), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.JUNGLE_BOAT), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.DARK_OAK_BOAT), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FLINT_AND_STEEL, 1, 32767), (new AspectList()).add(Aspect.FIRE, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FISHING_ROD, 1, 32767), (new AspectList()).add(Aspect.WATER, 1).add(Aspect.TOOL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.BUCKET), (new AspectList()).add(Aspect.METAL, 8).add(Aspect.VOID, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.WATER_BUCKET), (new AspectList(new ItemStack(Items.BUCKET))).add(Aspect.WATER, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.LAVA_BUCKET), (new AspectList(new ItemStack(Items.BUCKET))).add(Aspect.FIRE, 4).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.MILK_BUCKET), (new AspectList(new ItemStack(Items.BUCKET))).add(Aspect.HUNGER, 2).add(Aspect.HEAL, 2).add(Aspect.WATER, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Items.CAKE, 32767), (new AspectList()).add(Aspect.WATER, 4).add(Aspect.HUNGER, 4).add(Aspect.LIFE, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BREWING_STAND), (new AspectList()).add(Aspect.CRAFT, 2).add(Aspect.WATER, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.STONE_BUTTON), (new AspectList()).add(Aspect.MECHANISM, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.RAIL, 1, 32767), (new AspectList()).add(Aspect.METAL, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DETECTOR_RAIL, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.GOLDEN_RAIL, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.ENERGY, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ACTIVATOR_RAIL, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.OAK_FENCE_GATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.BIRCH_FENCE_GATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.SPRUCE_FENCE_GATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ACACIA_FENCE_GATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.JUNGLE_FENCE_GATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DARK_OAK_FENCE_GATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.TRAVEL, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.WOODEN_PRESSURE_PLATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.STONE_PRESSURE_PLATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1).add(Aspect.SENSES, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.LEVER, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.REDSTONE_TORCH, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.PISTON, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.STICKY_PISTON, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 2).add(Aspect.MOTION, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.JUKEBOX), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.MECHANISM, 2).add(Aspect.AIR, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.NOTEBLOCK), (new AspectList()).add(Aspect.SENSES, 4).add(Aspect.MECHANISM, 1).add(Aspect.AIR, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.TRAPDOOR, 1, 32767), (new AspectList()).add(Aspect.MOTION, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.LIT_FURNACE, 1, 32767), (new AspectList()).add(Aspect.FIRE, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.FURNACE, 1, 32767), (new AspectList()).add(Aspect.FIRE, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ENCHANTING_TABLE), (new AspectList()).add(Aspect.MAGIC, 8).add(Aspect.CRAFT, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CRAFTING_TABLE), (new AspectList()).add(Aspect.CRAFT, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.CLOCK), (new AspectList()).add(Aspect.MECHANISM, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.ANVIL), new int[]{0, 1, 2}, (new AspectList()).add(Aspect.METAL, 64).add(Aspect.CRAFT, 2).add(Aspect.TOOL, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.BEACON), (new AspectList()).add(Aspect.AURA, 2).add(Aspect.MAGIC, 2).add(Aspect.EXCHANGE, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.WOODEN_BUTTON, 1, 32767), (new AspectList()).add(Aspect.MECHANISM, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.CARROT_ON_A_STICK, 1, 32767), (new AspectList()).add(Aspect.TRAVEL, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FLOWER_POT), (new AspectList()).add(Aspect.VOID, 1).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GOLDEN_CARROT), (new AspectList()).add(Aspect.SENSES, 2));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ENDER_CHEST, 1, 32767), (new AspectList()).merge(Aspect.EXCHANGE, 2).merge(Aspect.TRAVEL, 2).merge(Aspect.VOID, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.HOPPER, 1, 32767), (new AspectList()).merge(Aspect.MECHANISM, 1).merge(Aspect.EXCHANGE, 1).merge(Aspect.VOID, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DROPPER, 1, 32767), (new AspectList()).merge(Aspect.MECHANISM, 1).merge(Aspect.EXCHANGE, 1).merge(Aspect.VOID, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DISPENSER, 1, 32767), (new AspectList()).merge(Aspect.MECHANISM, 1).merge(Aspect.EXCHANGE, 1).merge(Aspect.VOID, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.TRIPWIRE_HOOK, 1, 32767), (new AspectList()).add(Aspect.SENSES, 1).add(Aspect.MECHANISM, 1).add(Aspect.TRAP, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DAYLIGHT_DETECTOR, 1, 32767), (new AspectList()).merge(Aspect.SENSES, 2).merge(Aspect.LIGHT, 3).merge(Aspect.MECHANISM, 3));
      Map<List<PotionEffect>,Integer> lhm = new LinkedHashMap<>();
      for(int var4 = 1; var4 <= 0; ++var4) { // disabled
         List<PotionEffect> var5 = null; // was PotionHelper.getPotionEffects(var4, false)
         if (var5 != null && !var5.isEmpty()) {
            lhm.put(var5, var4);
         }
      }

      for(int var7 : lhm.values()) {
         ThaumcraftApi.registerObjectTag(new ItemStack(Items.POTIONITEM, 1, var7), new AspectList(new ItemStack(Items.POTIONITEM)));
      }

      ThaumcraftApi.registerComplexObjectTag(new ItemStack(ConfigBlocks.blockTable), (new AspectList()).add(Aspect.TOOL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTable, 1, 15), (new AspectList(new ItemStack(ConfigBlocks.blockTable))).add(Aspect.CRAFT, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTable, 1, 2), (new AspectList(new ItemStack(ConfigBlocks.blockTable))).add(Aspect.MIND, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 16), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 6).add(Aspect.EARTH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 31), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 4).add(Aspect.EARTH, 1).add(Aspect.GREED, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 21), (new AspectList()).add(Aspect.ORDER, 1).add(Aspect.METAL, 4).add(Aspect.EARTH, 1).add(Aspect.EXCHANGE, 4).add(Aspect.POISON, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 5), (new AspectList()).add(Aspect.METAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNugget, 1, 6), (new AspectList()).add(Aspect.METAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 0), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.METAL, 2).add(Aspect.EXCHANGE, 2).add(Aspect.POISON, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 7), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.TRAP, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 1), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.AIR, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 2), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.FIRE, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 3), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.WATER, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 4), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.EARTH, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 5), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ORDER, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomOre, 1, 6), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ENTROPY, 3).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaint, 1, 0), (new AspectList()).add(Aspect.TREE, 1).add(Aspect.TAINT, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaint, 1, 1), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.TAINT, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaintFibres, 1, 0), (new AspectList()).add(Aspect.LIFE, 1).add(Aspect.TAINT, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaintFibres, 1, 1), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.TAINT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaintFibres, 1, 2), (new AspectList()).add(Aspect.PLANT, 1).add(Aspect.TAINT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaintFibres, 1, 3), (new AspectList()).add(Aspect.BEAST, 1).add(Aspect.PLANT, 1).add(Aspect.TAINT, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockTaintFibres, 1, 4), (new AspectList()).add(Aspect.BEAST, 1).add(Aspect.PLANT, 1).add(Aspect.TAINT, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCosmeticSolid), (new AspectList()).add(Aspect.EARTH, 4).add(Aspect.DARKNESS, 2).add(Aspect.ELDRITCH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockMagicalLog, 1, 0), (new AspectList()).add(Aspect.TREE, 3).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockMagicalLog, 1, 1), (new AspectList()).add(Aspect.TREE, 3).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockMagicalLeaves, 1, 0), (new AspectList()).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockMagicalLeaves, 1, 1), (new AspectList()).add(Aspect.PLANT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomPlant, 1, 0), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.TREE, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomPlant, 1, 1), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.TREE, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomPlant, 1, 2), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.EXCHANGE, 2).add(Aspect.MAGIC, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomPlant, 1, 3), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.FIRE, 2).add(Aspect.MAGIC, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCustomPlant, 1, 5), (new AspectList()).add(Aspect.PLANT, 2).add(Aspect.POISON, 1).add(Aspect.MAGIC, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCosmeticSolid, 1, 6), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCosmeticSolid, 1, 7), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 3), (new AspectList()).add(Aspect.METAL, 3).add(Aspect.POISON, 1).add(Aspect.EXCHANGE, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemZombieBrain), (new AspectList()).add(Aspect.FLESH, 2).add(Aspect.MIND, 4).add(Aspect.UNDEAD, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 6), (new AspectList()).add(Aspect.TRAP, 2).add(Aspect.CRYSTAL, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 9), (new AspectList()).add(Aspect.MIND, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 11), (new AspectList()).add(Aspect.TAINT, 3).add(Aspect.SLIME, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 12), (new AspectList()).add(Aspect.TAINT, 2).add(Aspect.GREED, 1).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 18), (new AspectList()).add(Aspect.GREED, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemLootbag, 1, 0), (new AspectList()).add(Aspect.GREED, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemLootbag, 1, 1), (new AspectList()).add(Aspect.GREED, 16));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemLootbag, 1, 2), (new AspectList()).add(Aspect.GREED, 32));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNuggetBeef, 1, 32767), (new AspectList()).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNuggetChicken, 1, 32767), (new AspectList()).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNuggetPork, 1, 32767), (new AspectList()).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemNuggetFish, 1, 32767), (new AspectList()).add(Aspect.HUNGER, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(ConfigItems.itemTripleMeatTreat, 1, 32767), (new AspectList()).add(Aspect.HEAL, 1).remove(Aspect.HUNGER, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemShard, 1, 0), (new AspectList()).add(Aspect.MAGIC, 1).add(Aspect.AIR, 2).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemShard, 1, 1), (new AspectList()).add(Aspect.MAGIC, 1).add(Aspect.FIRE, 2).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemShard, 1, 2), (new AspectList()).add(Aspect.MAGIC, 1).add(Aspect.WATER, 2).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemShard, 1, 3), (new AspectList()).add(Aspect.MAGIC, 1).add(Aspect.EARTH, 2).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemShard, 1, 4), (new AspectList()).add(Aspect.MAGIC, 1).add(Aspect.ORDER, 2).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemShard, 1, 5), (new AspectList()).add(Aspect.MAGIC, 1).add(Aspect.ENTROPY, 2).add(Aspect.CRYSTAL, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemResource, 1, 14), (new AspectList(new ItemStack(ConfigItems.itemShard, 1, 6))).add(Aspect.MAGIC, 2).remove(Aspect.CRYSTAL));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockMetalDevice), (new AspectList(new ItemStack(Items.CAULDRON, 1, 32767))).add(Aspect.CRAFT, 4).add(Aspect.MAGIC, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCandle), (new AspectList()).add(Aspect.LIGHT, 2).add(Aspect.FLESH, 1).add(Aspect.MAGIC, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockAiry, 1, 2), (new AspectList()).add(Aspect.LIGHT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockAiry, 1, 3), (new AspectList()).add(Aspect.LIGHT, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemThaumonomicon, 1, 32767), (new AspectList(new ItemStack(Blocks.BOOKSHELF))).add(Aspect.MAGIC, 2).merge(Aspect.MIND, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockAlchemyFurnace, 1, 32767), (new AspectList()).add(Aspect.MAGIC, 8).add(Aspect.WATER, 8).add(Aspect.CRAFT, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemEssence, 1, 0), (new AspectList()).add(Aspect.VOID, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemEssence, 1, 1), new AspectList());
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemWispEssence, 1, 0), (new AspectList()).add(Aspect.AURA, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemCrystalEssence, 1, 0), new AspectList());
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(ConfigItems.itemPrimalArrow), (new AspectList()).add(Aspect.WEAPON, 1));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(ConfigItems.itemGoggles, 1, 32767), (new AspectList()).add(Aspect.SENSES, 4));
      ThaumcraftApi.registerComplexObjectTag(new ItemStack(ConfigBlocks.blockWoodenDevice, 1, 1), (new AspectList()).add(Aspect.SENSES, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemBaubleBlanks, 1, 3), (new AspectList()).add(Aspect.MAGIC, 5));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemFocusPech), (new AspectList()).add(Aspect.MAGIC, 5).add(Aspect.POISON, 5).add(Aspect.ENTROPY, 5).add(Aspect.ELDRITCH, 5).add(Aspect.WEAPON, 5));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemChestCultistPlate, 1, 32767), (new AspectList()).add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemChestCultistRobe, 1, 32767), (new AspectList()).add(Aspect.METAL, 3).add(Aspect.CLOTH, 2).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemChestCultistLeaderPlate, 1, 32767), (new AspectList()).add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemLegsCultistPlate, 1, 32767), (new AspectList()).add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemLegsCultistLeaderPlate, 1, 32767), (new AspectList()).add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemLegsCultistRobe, 1, 32767), (new AspectList()).add(Aspect.METAL, 3).add(Aspect.CLOTH, 2).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemHelmetCultistPlate, 1, 32767), (new AspectList()).add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemHelmetCultistLeaderPlate, 1, 32767), (new AspectList()).add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 2));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemHelmetCultistRobe, 1, 32767), (new AspectList()).add(Aspect.METAL, 3).add(Aspect.CLOTH, 2).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemBootsCultist, 1, 32767), (new AspectList()).add(Aspect.METAL, 4).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockWoodenDevice, 1, 8), (new AspectList()).add(Aspect.ELDRITCH, 1).add(Aspect.TREE, 2).add(Aspect.CLOTH, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemEldritchObject, 1, 0), (new AspectList()).add(Aspect.ELDRITCH, 5).add(Aspect.AURA, 3).add(Aspect.MAGIC, 3).add(Aspect.SENSES, 3).add(Aspect.SOUL, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemEldritchObject, 1, 1), (new AspectList()).add(Aspect.MIND, 5).add(Aspect.MAGIC, 3).add(Aspect.ELDRITCH, 3).add(Aspect.SOUL, 3));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemEldritchObject, 1, 2), (new AspectList()).add(Aspect.TRAP, 4).add(Aspect.MIND, 4).add(Aspect.MECHANISM, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigItems.itemEldritchObject, 1, 3), (new AspectList()).add(Aspect.AIR, 16).add(Aspect.EARTH, 16).add(Aspect.FIRE, 16).add(Aspect.WATER, 16).add(Aspect.ORDER, 16).add(Aspect.ENTROPY, 16));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockEldritch, 1, 32767), (new AspectList()).add(Aspect.VOID, 8).add(Aspect.ELDRITCH, 8).add(Aspect.SENSES, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockEldritchPortal), (new AspectList()).add(Aspect.VOID, 8).add(Aspect.ELDRITCH, 8).add(Aspect.TRAVEL, 8));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockEldritch, 1, 3), (new AspectList()).add(Aspect.VOID, 4).add(Aspect.ELDRITCH, 4));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockEldritch, 1, 4), (new AspectList()).add(Aspect.LIGHT, 1).add(Aspect.EARTH, 1).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockEldritch, 1, 5), (new AspectList()).add(Aspect.MIND, 2).add(Aspect.EARTH, 1).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockEldritch, 1, 6), (new AspectList()).add(Aspect.METAL, 2).add(Aspect.MECHANISM, 2).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCosmeticSolid, 1, 11), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ELDRITCH, 1));
      ThaumcraftApi.registerObjectTag(new ItemStack(ConfigBlocks.blockCosmeticSolid, 1, 12), (new AspectList()).add(Aspect.EARTH, 1).add(Aspect.ELDRITCH, 1));
   }
}
